=== ctorrescuadra/TaesLab/Examples/Templates/plant_model.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$ref": "#/definitions/DataModel",
	"definitions": {
		"DataModel": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"ProductiveStructure": {
					"$ref": "#/definitions/ProductiveStructure"
				},
				"ExergyStates": {
					"$ref": "#/definitions/ExergyStates"
				},
				"WasteDefinition": {
					"$ref": "#/definitions/WasteDefinition"
				},
				"ResourcesCost": {
					"$ref": "#/definitions/ResourcesCost"
				},
				"Format": {
					"$ref": "#/definitions/Format"
				}
			},
			"required": [
				"ProductiveStructure",
				"ExergyStates"
			]
		},
		"ProductiveStructure": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"flows": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Flow"
					}
				},
				"processes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Process"
					}
				}
			},
			"required": [
				"flows",
				"processes"
			]
		},
		"Flow": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"type": {
					"type": "string",
					"enum": [
						"INTERNAL",
						"RESOURCE",
						"OUTPUT",
						"WASTE"
					]
				}
			},
			"required": [
				"key",
				"type"
			]
		},
		"Process": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"description": {
					"type": "string"
				},
				"fuel": {
					"type": "string"
				},
				"product": {
					"type": "string"
				},
				"type": {
					"type": "string",
					"enum": [
						"PRODUCTIVE",
						"DISSIPATIVE"
					]
				}
			},
			"required": [
				"key",
				"description",
				"fuel",
				"product",
				"type"
			]
		},
		"ExergyStates": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"States": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/State"
					}
				}
			},
			"required": [
				"States"
			]
		},
		"State": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"stateId": {
					"type": "string"
				},
				"exergy": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				}
			},
			"required": [
				"exergy",
				"stateId"
			]
		},
		"Format": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"definitions": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/FormatDefinition"
					}
				}
			},
			"required": [
				"definitions"
			]
		},
		"FormatDefinition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"type": "string",
					"enum": [
						"EXERGY",
						"EXERGY_COST",
						"EXERGY_UNIT_COST",
						"GENERALIZED_COST",
						"GENERALIZED_UNIT_COST",
						"DIAGNOSIS"
					]
				},
				"width": {
					"type": "integer",
					"minimum": 1
				},
				"precision": {
					"type": "integer",
					"minimum": 0
				},
				"unit": {
					"type": "string"
				}
			},
			"required": [
				"key",
				"precision",
				"unit",
				"width"
			]
		},
		"ResourcesCost": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"Samples": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Sample"
					}
				}
			},
			"required": [
				"Samples"
			]
		},
		"Sample": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"sampleId": {
					"type": "string"
				},
				"flows": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				},
				"processes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				}
			},
			"required": [
				"sampleId",
				"flows"
			]
		},
		"WasteDefinition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"wastes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Wastes"
					}
				}
			},
			"required": [
				"wastes"
			]
		},
		"Wastes": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"flow": {
					"$ref": "#/definitions/Keys"
				},
				"type": {
					"type": "string",
					"enum": [
						"DEFAULT",
						"MANUAL",
						"RESOURCES",
						"EXERGY",
						"COST",
						"IRREVERSIBILITY",
						"HYBRID"
					]
				},
				"recycle": {
					"type": "number",
					"minimum": 0,
					"maximum": 1
				},
				"values": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/WasteAllocation"
					}
				}
			},
			"required": [
				"flow",
				"type"
			]
		},
		"WasteAllocation": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"process": {
					"$ref": "#/definitions/Keys"
				},
				"value": {
					"type": "number",
					"minimum": 0
				}
			},
			"required": [
				"process",
				"value"
			]
		},
		"Values": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"value": {
					"type": "number",
					"minimum": 0
				}
			},
			"required": [
				"key",
				"value"
			]
		},
		"Keys": {
			"type": "string",
			"pattern": "^[A-Z][A-Za-z0-9]+$"
		}
	}
}

=== ctorrescuadra/TaesLab/Examples/cogen/cogen_model.json
{
	"ProductiveStructure": {
		"flows": [
			{
				"key": "B1",
				"type": "INTERNAL"
			},
			{
				"key": "B2",
				"type": "INTERNAL"
			},
			{
				"key": "B3",
				"type": "INTERNAL"
			},
			{
				"key": "B4",
				"type": "INTERNAL"
			},
			{
				"key": "B5",
				"type": "RESOURCE"
			},
			{
				"key": "B6",
				"type": "INTERNAL"
			},
			{
				"key": "B7",
				"type": "INTERNAL"
			},
			{
				"key": "B8",
				"type": "OUTPUT"
			},
			{
				"key": "B9",
				"type": "OUTPUT"
			}
		],
		"processes": [
			{
				"key": "BOIL",
				"description": "Boiler",
				"fuel": "B5",
				"product": "B1-B4",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TURB",
				"description": "Turbine",
				"fuel": "B1-B2",
				"product": "B6",
				"type": "PRODUCTIVE"
			},
			{
				"key": "HEAT",
				"description": "Heat Exchanger",
				"fuel": "B2-B3",
				"product": "B9",
				"type": "PRODUCTIVE"
			},
			{
				"key": "PUMP",
				"description": "Pump",
				"fuel": "B7",
				"product": "B4-B3",
				"type": "PRODUCTIVE"
			},
			{
				"key": "ALTR",
				"description": "Alternator",
				"fuel": "B6",
				"product": "B7+B8",
				"type": "PRODUCTIVE"
			}
		]
	},
	"ExergyStates": {
		"States": [
			{
				"stateId": "Reference",
				"exergy": [
					{
						"key": "B1",
						"value": 30299
					},
					{
						"key": "B2",
						"value": 19111
					},
					{
						"key": "B3",
						"value": 2935
					},
					{
						"key": "B4",
						"value": 3184
					},
					{
						"key": "B5",
						"value": 64119
					},
					{
						"key": "B6",
						"value": 10485
					},
					{
						"key": "B7",
						"value": 275.3
					},
					{
						"key": "B8",
						"value": 10000
					},
					{
						"key": "B9",
						"value": 15021
					}
				]
			},
			{
				"stateId": "TP15",
				"exergy": [
					{
						"key": "B1",
						"value": 30304
					},
					{
						"key": "B2",
						"value": 19114
					},
					{
						"key": "B3",
						"value": 3101
					},
					{
						"key": "B4",
						"value": 3352
					},
					{
						"key": "B5",
						"value": 63583
					},
					{
						"key": "B6",
						"value": 10487
					},
					{
						"key": "B7",
						"value": 277.1
					},
					{
						"key": "B8",
						"value": 10000
					},
					{
						"key": "B9",
						"value": 14867
					}
				]
			},
			{
				"stateId": "ALT97",
				"exergy": [
					{
						"key": "B1",
						"value": 30620
					},
					{
						"key": "B2",
						"value": 19314
					},
					{
						"key": "B3",
						"value": 2966
					},
					{
						"key": "B4",
						"value": 3217
					},
					{
						"key": "B5",
						"value": 64799
					},
					{
						"key": "B6",
						"value": 10596
					},
					{
						"key": "B7",
						"value": 278.2
					},
					{
						"key": "B8",
						"value": 10000
					},
					{
						"key": "B9",
						"value": 15181
					}
				]
			},
			{
				"stateId": "T89",
				"exergy": [
					{
						"key": "B1",
						"value": 30649
					},
					{
						"key": "B2",
						"value": 19380
					},
					{
						"key": "B3",
						"value": 2969
					},
					{
						"key": "B4",
						"value": 3221
					},
					{
						"key": "B5",
						"value": 64860
					},
					{
						"key": "B6",
						"value": 10488
					},
					{
						"key": "B7",
						"value": 278.5
					},
					{
						"key": "B8",
						"value": 10000
					},
					{
						"key": "B9",
						"value": 15235
					}
				]
			},
			{
				"stateId": "t490",
				"exergy": [
					{
						"key": "B1",
						"value": 30529
					},
					{
						"key": "B2",
						"value": 19325
					},
					{
						"key": "B3",
						"value": 2991
					},
					{
						"key": "B4",
						"value": 3244
					},
					{
						"key": "B5",
						"value": 64679
					},
					{
						"key": "B6",
						"value": 10490
					},
					{
						"key": "B7",
						"value": 280.5
					},
					{
						"key": "B8",
						"value": 10000
					},
					{
						"key": "B9",
						"value": 15183
					}
				]
			},
			{
				"stateId": "p15",
				"exergy": [
					{
						"key": "B1",
						"value": 30354
					},
					{
						"key": "B2",
						"value": 19146
					},
					{
						"key": "B3",
						"value": 2940
					},
					{
						"key": "B4",
						"value": 3206
					},
					{
						"key": "B5",
						"value": 64214
					},
					{
						"key": "B6",
						"value": 10504
					},
					{
						"key": "B7",
						"value": 294
					},
					{
						"key": "B8",
						"value": 10000
					},
					{
						"key": "B9",
						"value": 15049
					}
				]
			}
		]
	},
	"ResourcesCost": {
		"Samples": [
			{
				"sampleId": "Base",
				"flows": [
					{
						"key": "B5",
						"value": 1.32
					}
				],
				"processes": [
					{
						"key": "BOIL",
						"value": 18000
					},
					{
						"key": "TURB",
						"value": 3000
					},
					{
						"key": "HEAT",
						"value": 500
					},
					{
						"key": "PUMP",
						"value": 0.1
					},
					{
						"key": "ALTR",
						"value": 1000
					}
				]
			}
		]
	},
	"Format": {
		"definitions": [
			{
				"key": "EXERGY",
				"width": 10,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "EXERGY_COST",
				"width": 10,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "EXERGY_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "(J/J)"
			},
			{
				"key": "GENERALIZED_COST",
				"width": 10,
				"precision": 1,
				"unit": "(c/h)"
			},
			{
				"key": "GENERALIZED_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "(c/kWh)"
			},
			{
				"key": "DIAGNOSIS",
				"width": 10,
				"precision": 2,
				"unit": "(kW)"
			}
		]
	}
}

=== ctorrescuadra/TaesLab/Examples/gpp/gpp_model.json
{
	"ProductiveStructure": {
		"flows": [
			{
				"key": "GTS",
				"type": "RESOURCE"
			},
			{
				"key": "B1",
				"type": "INTERNAL"
			},
			{
				"key": "B2",
				"type": "INTERNAL"
			},
			{
				"key": "B3",
				"type": "INTERNAL"
			},
			{
				"key": "B5",
				"type": "INTERNAL"
			},
			{
				"key": "B6",
				"type": "INTERNAL"
			},
			{
				"key": "B7",
				"type": "INTERNAL"
			},
			{
				"key": "B8",
				"type": "INTERNAL"
			},
			{
				"key": "V10",
				"type": "INTERNAL"
			},
			{
				"key": "V11",
				"type": "INTERNAL"
			},
			{
				"key": "V12",
				"type": "INTERNAL"
			},
			{
				"key": "V13",
				"type": "INTERNAL"
			},
			{
				"key": "V14",
				"type": "INTERNAL"
			},
			{
				"key": "V15",
				"type": "INTERNAL"
			},
			{
				"key": "V16",
				"type": "INTERNAL"
			},
			{
				"key": "V17",
				"type": "INTERNAL"
			},
			{
				"key": "V18",
				"type": "INTERNAL"
			},
			{
				"key": "V19",
				"type": "INTERNAL"
			},
			{
				"key": "V20",
				"type": "INTERNAL"
			},
			{
				"key": "W23",
				"type": "INTERNAL"
			},
			{
				"key": "W24",
				"type": "INTERNAL"
			},
			{
				"key": "W25",
				"type": "INTERNAL"
			},
			{
				"key": "W26",
				"type": "INTERNAL"
			},
			{
				"key": "W27",
				"type": "OUTPUT"
			},
			{
				"key": "Q28",
				"type": "WASTE"
			},
			{
				"key": "Q29",
				"type": "WASTE"
			}
		],
		"processes": [
			{
				"key": "GTS",
				"description": "Geotermal Source",
				"fuel": "GTS",
				"product": "B1-B6-B8",
				"type": "PRODUCTIVE"
			},
			{
				"key": "VAP1",
				"description": "Vaporizer 1",
				"fuel": "B1-B2",
				"product": "V10-V15",
				"type": "PRODUCTIVE"
			},
			{
				"key": "PHT1",
				"description": "Preheater 1",
				"fuel": "B5-B6",
				"product": "V14-V13",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TPHT",
				"description": "Top Preheater",
				"fuel": "B2-B3",
				"product": "V15-V14",
				"type": "PRODUCTIVE"
			},
			{
				"key": "VAP2",
				"description": "Vaporizer 2",
				"fuel": "B3-B5-B7",
				"product": "V16-V20",
				"type": "PRODUCTIVE"
			},
			{
				"key": "PHT2",
				"description": "Preheater 2",
				"fuel": "B7-B8",
				"product": "V20-V19",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TRB1",
				"description": "Organic Turbine 1",
				"fuel": "V10-V11",
				"product": "W23",
				"type": "PRODUCTIVE"
			},
			{
				"key": "PMP1",
				"description": "Cycle Pump 1",
				"fuel": "W25",
				"product": "V13-V12",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TRB2",
				"description": "Organic Turbine 2",
				"fuel": "V16-V17",
				"product": "W24",
				"type": "PRODUCTIVE"
			},
			{
				"key": "PMP2",
				"description": "Cycle Pump 2",
				"fuel": "W26",
				"product": "V19-V18",
				"type": "PRODUCTIVE"
			},
			{
				"key": "GEN",
				"description": "Generator",
				"fuel": "W23+W24",
				"product": "W25+W26+W27",
				"type": "PRODUCTIVE"
			},
			{
				"key": "CND1",
				"description": "AirCooler Conderser 1",
				"fuel": "V11-V12",
				"product": "Q28",
				"type": "DISSIPATIVE"
			},
			{
				"key": "CND2",
				"description": "AirCooler Condenser 2",
				"fuel": "V17-V18",
				"product": "Q29",
				"type": "DISSIPATIVE"
			}
		]
	},
	"ExergyStates": {
		"States": [
			{
				"stateId": "Reference",
				"exergy": [
					{
						"key": "GTS",
						"value": 47.13663024
					},
					{
						"key": "B1",
						"value": 60.37948494
					},
					{
						"key": "B2",
						"value": 39.00582594
					},
					{
						"key": "B3",
						"value": 33.3164664
					},
					{
						"key": "B5",
						"value": 13.43235312
					},
					{
						"key": "B6",
						"value": 6.36141789
					},
					{
						"key": "B7",
						"value": 13.43235312
					},
					{
						"key": "B8",
						"value": 6.88143681
					},
					{
						"key": "V10",
						"value": 28.5002048
					},
					{
						"key": "V11",
						"value": 6.64214304
					},
					{
						"key": "V12",
						"value": 0.20911648
					},
					{
						"key": "V13",
						"value": 0.68771296
					},
					{
						"key": "V14",
						"value": 4.90669184
					},
					{
						"key": "V15",
						"value": 9.40377408
					},
					{
						"key": "V16",
						"value": 9.19369068
					},
					{
						"key": "V17",
						"value": 2.37007
					},
					{
						"key": "V18",
						"value": 0.07847163
					},
					{
						"key": "V19",
						"value": 0.13760967
					},
					{
						"key": "V20",
						"value": 4.55362908
					},
					{
						"key": "W23",
						"value": 13.5729
					},
					{
						"key": "W24",
						"value": 4.18365
					},
					{
						"key": "W25",
						"value": 0.71277
					},
					{
						"key": "W26",
						"value": 0.08766
					},
					{
						"key": "W27",
						"value": 15.535596
					},
					{
						"key": "Q28",
						"value": 6.43302656
					},
					{
						"key": "Q29",
						"value": 2.29159905
					}
				]
			}
		]
	},
	"WasteDefinition": {
		"wastes": [
			{
				"flow": "Q28",
				"type": "MANUAL",
				"recycle": 0,
				"values": [
					{
						"process": "VAP1",
						"value": 4.342
					},
					{
						"process": "PHT1",
						"value": 0.959
					},
					{
						"process": "TPHT",
						"value": 1.023
					}
				]
			},
			{
				"flow": "Q29",
				"type": "MANUAL",
				"recycle": 0,
				"values": [
					{
						"process": "VAP2",
						"value": 1.167
					},
					{
						"process": "PHT2",
						"value": 1.11
					}
				]
			}
		]
	},
	"ResourcesCost": {
		"Samples": [
			{
				"sampleId": "Base",
				"flows": [
					{
						"key": "GTS",
						"value": 0
					}
				],
				"processes": [
					{
						"key": "GTS",
						"value": 2.016
					},
					{
						"key": "VAP1",
						"value": 22.285569084618874
					},
					{
						"key": "PHT1",
						"value": 40.277710276471652
					},
					{
						"key": "TPHT",
						"value": 11.652665142962849
					},
					{
						"key": "VAP2",
						"value": 25.339241921632429
					},
					{
						"key": "PHT2",
						"value": 11.36591179427392
					},
					{
						"key": "TRB1",
						"value": 12.413933996893435
					},
					{
						"key": "PMP1",
						"value": 1.6558322656713613
					},
					{
						"key": "TRB2",
						"value": 9.340597579858402
					},
					{
						"key": "PMP2",
						"value": 0.31553226694687342
					},
					{
						"key": "GEN",
						"value": 73.3754516213971
					},
					{
						"key": "CND1",
						"value": 103.59773535017091
					},
					{
						"key": "CND2",
						"value": 59.115402673146008
					}
				]
			},
			{
				"sampleId": "Operation",
				"flows": [
					{
						"key": "GTS",
						"value": 0.04
					}
				],
				"processes": [
					{
						"key": "GTS",
						"value": 2.016
					},
					{
						"key": "VAP1",
						"value": 20.057012176156988
					},
					{
						"key": "PHT1",
						"value": 36.249939248824489
					},
					{
						"key": "TPHT",
						"value": 10.487398628666565
					},
					{
						"key": "VAP2",
						"value": 22.805317729469188
					},
					{
						"key": "PHT2",
						"value": 10.229320614846529
					},
					{
						"key": "TRB1",
						"value": 11.172540597204092
					},
					{
						"key": "PMP1",
						"value": 1.4902490391042251
					},
					{
						"key": "TRB2",
						"value": 8.4065378218725613
					},
					{
						"key": "PMP2",
						"value": 0.28397904025218607
					},
					{
						"key": "GEN",
						"value": 66.0379064592574
					},
					{
						"key": "CND1",
						"value": 93.237961815153824
					},
					{
						"key": "CND2",
						"value": 53.203862405831408
					}
				]
			}
		]
	},
	"Format": {
		"definitions": [
			{
				"key": "EXERGY",
				"width": 10,
				"precision": 3,
				"unit": "(MW)"
			},
			{
				"key": "EXERGY_COST",
				"width": 10,
				"precision": 3,
				"unit": "(MW)"
			},
			{
				"key": "EXERGY_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "(J/J)"
			},
			{
				"key": "GENERALIZED_COST",
				"width": 10,
				"precision": 3,
				"unit": "($/h)"
			},
			{
				"key": "GENERALIZED_UNIT_COST",
				"width": 10,
				"precision": 3,
				"unit": "($/MWh)"
			},
			{
				"key": "DIAGNOSIS",
				"width": 10,
				"precision": 4,
				"unit": "(MW)"
			}
		]
	}
}

=== ctorrescuadra/TaesLab/Examples/polygen/polygen_model.json
{
	"ProductiveStructure": {
		"flows": [
			{
				"key": "B1",
				"type": "RESOURCE"
			},
			{
				"key": "B2",
				"type": "INTERNAL"
			},
			{
				"key": "B3",
				"type": "INTERNAL"
			},
			{
				"key": "B4",
				"type": "RESOURCE"
			},
			{
				"key": "B5",
				"type": "INTERNAL"
			},
			{
				"key": "B6",
				"type": "INTERNAL"
			},
			{
				"key": "B7",
				"type": "INTERNAL"
			},
			{
				"key": "B8",
				"type": "OUTPUT"
			},
			{
				"key": "B9",
				"type": "INTERNAL"
			},
			{
				"key": "B10",
				"type": "RESOURCE"
			},
			{
				"key": "B11",
				"type": "INTERNAL"
			},
			{
				"key": "B12",
				"type": "OUTPUT"
			},
			{
				"key": "B13",
				"type": "INTERNAL"
			},
			{
				"key": "B14",
				"type": "INTERNAL"
			},
			{
				"key": "B15",
				"type": "RESOURCE"
			},
			{
				"key": "B16",
				"type": "INTERNAL"
			},
			{
				"key": "B17",
				"type": "OUTPUT"
			},
			{
				"key": "B18",
				"type": "OUTPUT"
			},
			{
				"key": "B19",
				"type": "INTERNAL"
			},
			{
				"key": "B20",
				"type": "WASTE"
			}
		],
		"processes": [
			{
				"key": "COMB",
				"description": "Combustor",
				"fuel": "B4",
				"product": "B5-B3",
				"type": "PRODUCTIVE"
			},
			{
				"key": "REGE",
				"description": "Regenerator",
				"fuel": "B6-B9",
				"product": "B3-B2",
				"type": "PRODUCTIVE"
			},
			{
				"key": "COMP",
				"description": "Compressor",
				"fuel": "B7",
				"product": "B2-B1",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TURB",
				"description": "Turbine",
				"fuel": "B5-B6",
				"product": "B7+B8",
				"type": "PRODUCTIVE"
			},
			{
				"key": "ICE",
				"description": "ICE",
				"fuel": "B10",
				"product": "B11+B12+(B13-B14)",
				"type": "PRODUCTIVE"
			},
			{
				"key": "WHTR",
				"description": "Water Heater",
				"fuel": "B13-B14",
				"product": "B17",
				"type": "PRODUCTIVE"
			},
			{
				"key": "BURN",
				"description": "Burner",
				"fuel": "B15",
				"product": "B16-B11",
				"type": "PRODUCTIVE"
			},
			{
				"key": "HRSG",
				"description": "HRSG",
				"fuel": "B16+B9-B19",
				"product": "B18",
				"type": "PRODUCTIVE"
			},
			{
				"key": "STCK",
				"description": "Stack",
				"fuel": "B19",
				"product": "B20",
				"type": "DISSIPATIVE"
			}
		]
	},
	"ExergyStates": {
		"States": [
			{
				"stateId": "Reference",
				"exergy": [
					{
						"key": "B1",
						"value": 0
					},
					{
						"key": "B2",
						"value": 26204
					},
					{
						"key": "B3",
						"value": 41732
					},
					{
						"key": "B4",
						"value": 78643
					},
					{
						"key": "B5",
						"value": 94210
					},
					{
						"key": "B6",
						"value": 33696
					},
					{
						"key": "B7",
						"value": 27939
					},
					{
						"key": "B8",
						"value": 30000
					},
					{
						"key": "B9",
						"value": 16271
					},
					{
						"key": "B10",
						"value": 27568
					},
					{
						"key": "B11",
						"value": 3949
					},
					{
						"key": "B12",
						"value": 10000
					},
					{
						"key": "B13",
						"value": 3116
					},
					{
						"key": "B14",
						"value": 2357
					},
					{
						"key": "B15",
						"value": 10717
					},
					{
						"key": "B16",
						"value": 10073
					},
					{
						"key": "B17",
						"value": 375
					},
					{
						"key": "B18",
						"value": 14060
					},
					{
						"key": "B19",
						"value": 4129
					},
					{
						"key": "B20",
						"value": 4129
					}
				]
			}
		]
	},
	"WasteDefinition": {
		"wastes": [
			{
				"flow": "B20",
				"type": "DEFAULT",
				"recycle": 0
			}
		]
	},
	"ResourcesCost": {
		"Samples": [
			{
				"sampleId": "Base",
				"flows": [
					{
						"key": "B4",
						"value": 1.284
					},
					{
						"key": "B10",
						"value": 1.475
					},
					{
						"key": "B15",
						"value": 1.346
					}
				]
			}
		]
	}
}

=== ctorrescuadra/TaesLab/Examples/rvpc/rvpc_model.json
{
	"ProductiveStructure": {
		"flows": [
			{
				"key": "B1",
				"type": "INTERNAL"
			},
			{
				"key": "B2",
				"type": "INTERNAL"
			},
			{
				"key": "B3",
				"type": "INTERNAL"
			},
			{
				"key": "B4",
				"type": "INTERNAL"
			},
			{
				"key": "B5",
				"type": "INTERNAL"
			},
			{
				"key": "B6",
				"type": "INTERNAL"
			},
			{
				"key": "B7",
				"type": "INTERNAL"
			},
			{
				"key": "AIR",
				"type": "RESOURCE"
			},
			{
				"key": "WT",
				"type": "INTERNAL"
			},
			{
				"key": "WBC",
				"type": "INTERNAL"
			},
			{
				"key": "WBA",
				"type": "INTERNAL"
			},
			{
				"key": "COMB",
				"type": "RESOURCE"
			},
			{
				"key": "WN",
				"type": "OUTPUT"
			},
			{
				"key": "QCON",
				"type": "WASTE"
			}
		],
		"processes": [
			{
				"key": "CALD",
				"description": "Caldera",
				"fuel": "COMB+AIR",
				"product": "B1-B7",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TURB",
				"description": "Turbina",
				"fuel": "B1-B2-B3",
				"product": "WT",
				"type": "PRODUCTIVE"
			},
			{
				"key": "BC",
				"description": "Bomba Condensados",
				"fuel": "WBC",
				"product": "B5-B4",
				"type": "PRODUCTIVE"
			},
			{
				"key": "DESG",
				"description": "Desgasificador",
				"fuel": "B2+B5",
				"product": "B6",
				"type": "PRODUCTIVE"
			},
			{
				"key": "BA",
				"description": "Bomba Alimentacion",
				"fuel": "WBA",
				"product": "B7-B6",
				"type": "PRODUCTIVE"
			},
			{
				"key": "GEN",
				"description": "Generador",
				"fuel": "WT",
				"product": "WN+WBC+WBA",
				"type": "PRODUCTIVE"
			},
			{
				"key": "COND",
				"description": "Condensador",
				"fuel": "B3-B4",
				"product": "QCON",
				"type": "DISSIPATIVE"
			}
		]
	},
	"ExergyStates": {
		"States": [
			{
				"stateId": "Reference",
				"exergy": [
					{
						"key": "B1",
						"value": 146374
					},
					{
						"key": "B2",
						"value": 16956
					},
					{
						"key": "B3",
						"value": 12183
					},
					{
						"key": "B4",
						"value": 256.9
					},
					{
						"key": "B5",
						"value": 315.6
					},
					{
						"key": "B6",
						"value": 12147
					},
					{
						"key": "B7",
						"value": 12993
					},
					{
						"key": "AIR",
						"value": 0
					},
					{
						"key": "WT",
						"value": 102964
					},
					{
						"key": "WBC",
						"value": 58.700000000000045
					},
					{
						"key": "WBA",
						"value": 846
					},
					{
						"key": "COMB",
						"value": 325246
					},
					{
						"key": "WN",
						"value": 100000
					},
					{
						"key": "QCON",
						"value": 11926.1
					}
				]
			},
			{
				"stateId": "PC10",
				"exergy": [
					{
						"key": "B1",
						"value": 146459
					},
					{
						"key": "B2",
						"value": 16966
					},
					{
						"key": "B3",
						"value": 12190
					},
					{
						"key": "B4",
						"value": 257.1
					},
					{
						"key": "B5",
						"value": 315.8
					},
					{
						"key": "B6",
						"value": 12154
					},
					{
						"key": "B7",
						"value": 13059
					},
					{
						"key": "AIR",
						"value": 0
					},
					{
						"key": "WT",
						"value": 103024
					},
					{
						"key": "WBC",
						"value": 58.8
					},
					{
						"key": "WBA",
						"value": 910
					},
					{
						"key": "COMB",
						"value": 325366
					},
					{
						"key": "WN",
						"value": 100000
					},
					{
						"key": "QCON",
						"value": 11932.9
					}
				]
			},
			{
				"stateId": "T84",
				"exergy": [
					{
						"key": "B1",
						"value": 147886
					},
					{
						"key": "B2",
						"value": 17139
					},
					{
						"key": "B3",
						"value": 12381
					},
					{
						"key": "B4",
						"value": 259.7
					},
					{
						"key": "B5",
						"value": 319
					},
					{
						"key": "B6",
						"value": 12273
					},
					{
						"key": "B7",
						"value": 13128
					},
					{
						"key": "AIR",
						"value": 0
					},
					{
						"key": "WT",
						"value": 102973
					},
					{
						"key": "WBC",
						"value": 60
					},
					{
						"key": "WBA",
						"value": 860
					},
					{
						"key": "COMB",
						"value": 328605
					},
					{
						"key": "WN",
						"value": 100000
					},
					{
						"key": "QCON",
						"value": 12121.3
					}
				]
			}
		]
	},
	"WasteDefinition": {
		"wastes": [
			{
				"flow": "QCON",
				"type": "MANUAL",
				"recycle": 0,
				"values": [
					{
						"process": "CALD",
						"value": 0.92
					},
					{
						"process": "DESG",
						"value": 0.08
					}
				]
			}
		]
	},
	"Format": {
		"definitions": [
			{
				"key": "EXERGY",
				"width": 10,
				"precision": 1,
				"unit": "[kW]"
			},
			{
				"key": "EXERGY_COST",
				"width": 10,
				"precision": 1,
				"unit": "[kW]"
			},
			{
				"key": "EXERGY_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "[J/J]"
			},
			{
				"key": "GENERALIZED_COST",
				"width": 10,
				"precision": 1,
				"unit": "[kW]"
			},
			{
				"key": "GENERALIZED_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "[J/J]"
			},
			{
				"key": "DIAGNOSIS",
				"width": 10,
				"precision": 2,
				"unit": "[kW]"
			}
		]
	}
}
