=== ctorrescuadra/TaesLab/Examples/Templates/plant_model.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$ref": "#/definitions/DataModel",
	"definitions": {
		"DataModel": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"ProductiveStructure": {
					"$ref": "#/definitions/ProductiveStructure"
				},
				"ExergyStates": {
					"$ref": "#/definitions/ExergyStates"
				},
				"WasteDefinition": {
					"$ref": "#/definitions/WasteDefinition"
				},
				"ResourcesCost": {
					"$ref": "#/definitions/ResourcesCost"
				},
				"Format": {
					"$ref": "#/definitions/Format"
				}
			},
			"required": [
				"ProductiveStructure",
				"ExergyStates"
			]
		},
		"ProductiveStructure": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"flows": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Flow"
					}
				},
				"processes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Process"
					}
				}
			},
			"required": [
				"flows",
				"processes"
			]
		},
		"Flow": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"type": {
					"type": "string",
					"enum": [
						"INTERNAL",
						"RESOURCE",
						"OUTPUT",
						"WASTE"
					]
				}
			},
			"required": [
				"key",
				"type"
			]
		},
		"Process": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"description": {
					"type": "string"
				},
				"fuel": {
					"type": "string"
				},
				"product": {
					"type": "string"
				},
				"type": {
					"type": "string",
					"enum": [
						"PRODUCTIVE",
						"DISSIPATIVE"
					]
				}
			},
			"required": [
				"key",
				"description",
				"fuel",
				"product",
				"type"
			]
		},
		"ExergyStates": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"States": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/State"
					}
				}
			},
			"required": [
				"States"
			]
		},
		"State": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"stateId": {
					"type": "string"
				},
				"exergy": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				}
			},
			"required": [
				"exergy",
				"stateId"
			]
		},
		"Format": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"definitions": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/FormatDefinition"
					}
				}
			},
			"required": [
				"definitions"
			]
		},
		"FormatDefinition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"type": "string",
					"enum": [
						"EXERGY",
						"EXERGY_COST",
						"EXERGY_UNIT_COST",
						"GENERALIZED_COST",
						"GENERALIZED_UNIT_COST",
						"DIAGNOSIS"
					]
				},
				"width": {
					"type": "integer",
					"minimum": 1
				},
				"precision": {
					"type": "integer",
					"minimum": 0
				},
				"unit": {
					"type": "string"
				}
			},
			"required": [
				"key",
				"precision",
				"unit",
				"width"
			]
		},
		"ResourcesCost": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"Samples": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Sample"
					}
				}
			},
			"required": [
				"Samples"
			]
		},
		"Sample": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"sampleId": {
					"type": "string"
				},
				"flows": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				},
				"processes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				}
			},
			"required": [
				"sampleId",
				"flows"
			]
		},
		"WasteDefinition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"wastes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Wastes"
					}
				}
			},
			"required": [
				"wastes"
			]
		},
		"Wastes": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"flow": {
					"$ref": "#/definitions/Keys"
				},
				"type": {
					"type": "string",
					"enum": [
						"DEFAULT",
						"MANUAL",
						"RESOURCES",
						"EXERGY",
						"COST",
						"IRREVERSIBILITY",
						"HYBRID"
					]
				},
				"recycle": {
					"type": "number",
					"minimum": 0,
					"maximum": 1
				},
				"values": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/WasteAllocation"
					}
				}
			},
			"required": [
				"flow",
				"type"
			]
		},
		"WasteAllocation": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"process": {
					"$ref": "#/definitions/Keys"
				},
				"value": {
					"type": "number",
					"minimum": 0
				}
			},
			"required": [
				"process",
				"value"
			]
		},
		"Values": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"value": {
					"type": "number",
					"minimum": 0
				}
			},
			"required": [
				"key",
				"value"
			]
		},
		"Keys": {
			"type": "string",
			"pattern": "^[A-Z][A-Za-z0-9]+$"
		}
	}
}

=== ctorrescuadra/TaesLab/Examples/tgas/tgas_model.json
{
	"ProductiveStructure": {
		"flows": [
			{
				"key": "NG",
				"type": "RESOURCE"
			},
			{
				"key": "B2",
				"type": "INTERNAL"
			},
			{
				"key": "B3",
				"type": "INTERNAL"
			},
			{
				"key": "B4",
				"type": "INTERNAL"
			},
			{
				"key": "B5",
				"type": "INTERNAL"
			},
			{
				"key": "WC",
				"type": "INTERNAL"
			},
			{
				"key": "WN",
				"type": "OUTPUT"
			},
			{
				"key": "QV",
				"type": "OUTPUT"
			},
			{
				"key": "QG",
				"type": "WASTE"
			}
		],
		"processes": [
			{
				"key": "COMB",
				"description": "Combustor",
				"fuel": "NG",
				"product": "B3-B2",
				"type": "PRODUCTIVE"
			},
			{
				"key": "COMP",
				"description": "Compressor",
				"fuel": "WC",
				"product": "B2",
				"type": "PRODUCTIVE"
			},
			{
				"key": "GTRB",
				"description": "Turbine",
				"fuel": "B3-B4",
				"product": "WC+WN",
				"type": "PRODUCTIVE"
			},
			{
				"key": "HRSG",
				"description": "HRSG",
				"fuel": "B4-B5",
				"product": "QV",
				"type": "PRODUCTIVE"
			},
			{
				"key": "STCK",
				"description": "Stack",
				"fuel": "B5",
				"product": "QG",
				"type": "DISSIPATIVE"
			}
		]
	},
	"ExergyStates": {
		"States": [
			{
				"stateId": "Reference",
				"exergy": [
					{
						"key": "NG",
						"value": 36620
					},
					{
						"key": "B2",
						"value": 9512
					},
					{
						"key": "B3",
						"value": 32990
					},
					{
						"key": "B4",
						"value": 11707
					},
					{
						"key": "B5",
						"value": 835.3
					},
					{
						"key": "WC",
						"value": 10225
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QV",
						"value": 7168
					},
					{
						"key": "QG",
						"value": 835.3
					}
				]
			},
			{
				"stateId": "TURB86",
				"exergy": [
					{
						"key": "NG",
						"value": 37491
					},
					{
						"key": "B2",
						"value": 9739
					},
					{
						"key": "B3",
						"value": 33775
					},
					{
						"key": "B4",
						"value": 12143
					},
					{
						"key": "B5",
						"value": 1073
					},
					{
						"key": "WC",
						"value": 10468
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QV",
						"value": 7168
					},
					{
						"key": "QG",
						"value": 1073
					}
				]
			},
			{
				"stateId": "COMP86",
				"exergy": [
					{
						"key": "NG",
						"value": 36939
					},
					{
						"key": "B2",
						"value": 9686
					},
					{
						"key": "B3",
						"value": 33389
					},
					{
						"key": "B4",
						"value": 11848
					},
					{
						"key": "B5",
						"value": 917.9
					},
					{
						"key": "WC",
						"value": 10470
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QV",
						"value": 7168
					},
					{
						"key": "QG",
						"value": 917.9
					}
				]
			},
			{
				"stateId": "T25",
				"exergy": [
					{
						"key": "NG",
						"value": 36905
					},
					{
						"key": "B2",
						"value": 9903
					},
					{
						"key": "B3",
						"value": 33419
					},
					{
						"key": "B4",
						"value": 11673
					},
					{
						"key": "B5",
						"value": 888.2
					},
					{
						"key": "WC",
						"value": 10645
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QV",
						"value": 7168
					},
					{
						"key": "QG",
						"value": 888.2
					}
				]
			},
			{
				"stateId": "ECTR",
				"exergy": [
					{
						"key": "NG",
						"value": 36620
					},
					{
						"key": "B2",
						"value": 9512
					},
					{
						"key": "B3",
						"value": 32990
					},
					{
						"key": "B4",
						"value": 11707
					},
					{
						"key": "B5",
						"value": 548.6
					},
					{
						"key": "WC",
						"value": 10225
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QV",
						"value": 7545
					},
					{
						"key": "QG",
						"value": 548.6
					}
				]
			}
		]
	},
	"WasteDefinition": {
		"wastes": [
			{
				"flow": "QG",
				"type": "DEFAULT",
				"recycle": 0,
				"values": [
					{
						"process": "COMB",
						"value": 0.75
					},
					{
						"process": "COMP",
						"value": 0.25
					}
				]
			}
		]
	},
	"ResourcesCost": {
		"Samples": [
			{
				"sampleId": "Base",
				"flows": [
					{
						"key": "NG",
						"value": 1.32
					}
				],
				"processes": [
					{
						"key": "COMB",
						"value": 141.92
					},
					{
						"key": "COMP",
						"value": 1216.38
					},
					{
						"key": "GTRB",
						"value": 1662.4
					},
					{
						"key": "HRSG",
						"value": 1076.47
					},
					{
						"key": "STCK",
						"value": 0
					}
				]
			},
			{
				"sampleId": "STACK",
				"flows": [
					{
						"key": "NG",
						"value": 1.082
					}
				],
				"processes": [
					{
						"key": "COMB",
						"value": 141.92
					},
					{
						"key": "COMP",
						"value": 1216.38
					},
					{
						"key": "GTRB",
						"value": 1662.4
					},
					{
						"key": "HRSG",
						"value": 1076.47
					},
					{
						"key": "STCK",
						"value": 8715.56
					}
				]
			}
		]
	},
	"Format": {
		"definitions": [
			{
				"key": "EXERGY",
				"width": 10,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "EXERGY_COST",
				"width": 10,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "EXERGY_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "(J/J)"
			},
			{
				"key": "GENERALIZED_COST",
				"width": 10,
				"precision": 1,
				"unit": "(c/h)"
			},
			{
				"key": "GENERALIZED_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "(c/kWh)"
			},
			{
				"key": "DIAGNOSIS",
				"width": 10,
				"precision": 3,
				"unit": "(kW)"
			}
		]
	}
}

=== ctorrescuadra/TaesLab/Examples/cicloComb/cicloComb_model.json
{
	"ProductiveStructure": {
		"flows": [
			{
				"key": "A1",
				"type": "RESOURCE"
			},
			{
				"key": "A2",
				"type": "INTERNAL"
			},
			{
				"key": "A3",
				"type": "INTERNAL"
			},
			{
				"key": "A4",
				"type": "INTERNAL"
			},
			{
				"key": "A5",
				"type": "INTERNAL"
			},
			{
				"key": "A6",
				"type": "INTERNAL"
			},
			{
				"key": "A7",
				"type": "INTERNAL"
			},
			{
				"key": "V8",
				"type": "INTERNAL"
			},
			{
				"key": "V9",
				"type": "INTERNAL"
			},
			{
				"key": "V10",
				"type": "INTERNAL"
			},
			{
				"key": "V11",
				"type": "INTERNAL"
			},
			{
				"key": "V12",
				"type": "INTERNAL"
			},
			{
				"key": "V13",
				"type": "INTERNAL"
			},
			{
				"key": "GN",
				"type": "RESOURCE"
			},
			{
				"key": "WC",
				"type": "INTERNAL"
			},
			{
				"key": "WTG",
				"type": "INTERNAL"
			},
			{
				"key": "WTV",
				"type": "INTERNAL"
			},
			{
				"key": "WB",
				"type": "INTERNAL"
			},
			{
				"key": "WN",
				"type": "OUTPUT"
			},
			{
				"key": "QC",
				"type": "WASTE"
			},
			{
				"key": "QG",
				"type": "WASTE"
			}
		],
		"processes": [
			{
				"key": "COMB",
				"description": "Combustor",
				"fuel": "GN",
				"product": "A3-A2",
				"type": "PRODUCTIVE"
			},
			{
				"key": "COMP",
				"description": "Compresor",
				"fuel": "WC",
				"product": "A2-A1",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TGAS",
				"description": "Turbina Gas",
				"fuel": "A3-A4",
				"product": "WTG",
				"type": "PRODUCTIVE"
			},
			{
				"key": "SHT",
				"description": "Sobrecalentador",
				"fuel": "A4-A5",
				"product": "V13-V12",
				"type": "PRODUCTIVE"
			},
			{
				"key": "EVAP",
				"description": "Evaporador",
				"fuel": "A5-A6",
				"product": "V12-V11",
				"type": "PRODUCTIVE"
			},
			{
				"key": "ECON",
				"description": "Economizador",
				"fuel": "A6-A7",
				"product": "V11-V10",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TVAP",
				"description": "Turbina de vapor",
				"fuel": "V13-V8",
				"product": "WTV",
				"type": "PRODUCTIVE"
			},
			{
				"key": "PUMP",
				"description": "Bomba alimentacion",
				"fuel": "WB",
				"product": "V10-V9",
				"type": "PRODUCTIVE"
			},
			{
				"key": "ALTN",
				"description": "Alternador",
				"fuel": "(WTG-WC)+WTV",
				"product": "WB+WN",
				"type": "PRODUCTIVE"
			},
			{
				"key": "COND",
				"description": "Condensador",
				"fuel": "V8-V9",
				"product": "QC",
				"type": "DISSIPATIVE"
			},
			{
				"key": "STCK",
				"description": "Chimenea",
				"fuel": "A7",
				"product": "QG",
				"type": "DISSIPATIVE"
			}
		]
	},
	"ExergyStates": {
		"States": [
			{
				"stateId": "Reference",
				"exergy": [
					{
						"key": "A1",
						"value": 0
					},
					{
						"key": "A2",
						"value": 71.895
					},
					{
						"key": "A3",
						"value": 216.612
					},
					{
						"key": "A4",
						"value": 65.409
					},
					{
						"key": "A5",
						"value": 51.403
					},
					{
						"key": "A6",
						"value": 26.235
					},
					{
						"key": "A7",
						"value": 7.627
					},
					{
						"key": "V8",
						"value": 3.677
					},
					{
						"key": "V9",
						"value": 0.05675
					},
					{
						"key": "V10",
						"value": 0.4109
					},
					{
						"key": "V11",
						"value": 14.311
					},
					{
						"key": "V12",
						"value": 36.006
					},
					{
						"key": "V13",
						"value": 48.035
					},
					{
						"key": "GN",
						"value": 213.81
					},
					{
						"key": "WC",
						"value": 77.742
					},
					{
						"key": "WTG",
						"value": 142.202
					},
					{
						"key": "WTV",
						"value": 38.002
					},
					{
						"key": "WB",
						"value": 0.4127
					},
					{
						"key": "WN",
						"value": 100
					},
					{
						"key": "QC",
						"value": 3.401
					},
					{
						"key": "QG",
						"value": 7.627
					}
				]
			},
			{
				"stateId": "TG1",
				"exergy": [
					{
						"key": "A1",
						"value": 0
					},
					{
						"key": "A2",
						"value": 72.398
					},
					{
						"key": "A3",
						"value": 218.127
					},
					{
						"key": "A4",
						"value": 66.982
					},
					{
						"key": "A5",
						"value": 52.466
					},
					{
						"key": "A6",
						"value": 26.418
					},
					{
						"key": "A7",
						"value": 7.307
					},
					{
						"key": "V8",
						"value": 3.798
					},
					{
						"key": "V9",
						"value": 0.05861
					},
					{
						"key": "V10",
						"value": 0.4244
					},
					{
						"key": "V11",
						"value": 14.78
					},
					{
						"key": "V12",
						"value": 37.188
					},
					{
						"key": "V13",
						"value": 49.612
					},
					{
						"key": "GN",
						"value": 215.305
					},
					{
						"key": "WC",
						"value": 78.285
					},
					{
						"key": "WTG",
						"value": 141.511
					},
					{
						"key": "WTV",
						"value": 39.25
					},
					{
						"key": "WB",
						"value": 0.4263
					},
					{
						"key": "WN",
						"value": 100
					},
					{
						"key": "QC",
						"value": 3.512
					},
					{
						"key": "QG",
						"value": 7.307
					}
				]
			},
			{
				"stateId": "TV1",
				"exergy": [
					{
						"key": "A1",
						"value": 0
					},
					{
						"key": "A2",
						"value": 72.211
					},
					{
						"key": "A3",
						"value": 217.566
					},
					{
						"key": "A4",
						"value": 65.697
					},
					{
						"key": "A5",
						"value": 51.629
					},
					{
						"key": "A6",
						"value": 26.35
					},
					{
						"key": "A7",
						"value": 7.661
					},
					{
						"key": "V8",
						"value": 3.717
					},
					{
						"key": "V9",
						"value": 0.057
					},
					{
						"key": "V10",
						"value": 0.4127
					},
					{
						"key": "V11",
						"value": 14.373
					},
					{
						"key": "V12",
						"value": 36.164
					},
					{
						"key": "V13",
						"value": 48.246
					},
					{
						"key": "GN",
						"value": 214.751
					},
					{
						"key": "WC",
						"value": 78.084
					},
					{
						"key": "WTG",
						"value": 142.828
					},
					{
						"key": "WTV",
						"value": 37.72
					},
					{
						"key": "WB",
						"value": 0.4145
					},
					{
						"key": "WN",
						"value": 100
					},
					{
						"key": "QC",
						"value": 3.438
					},
					{
						"key": "QG",
						"value": 7.661
					}
				]
			},
			{
				"stateId": "ALT2",
				"exergy": [
					{
						"key": "A1",
						"value": 0
					},
					{
						"key": "A2",
						"value": 72.639
					},
					{
						"key": "A3",
						"value": 218.855
					},
					{
						"key": "A4",
						"value": 66.086
					},
					{
						"key": "A5",
						"value": 51.935
					},
					{
						"key": "A6",
						"value": 26.506
					},
					{
						"key": "A7",
						"value": 7.706
					},
					{
						"key": "V8",
						"value": 3.715
					},
					{
						"key": "V9",
						"value": 0.05734
					},
					{
						"key": "V10",
						"value": 0.4151
					},
					{
						"key": "V11",
						"value": 14.459
					},
					{
						"key": "V12",
						"value": 36.379
					},
					{
						"key": "V13",
						"value": 48.532
					},
					{
						"key": "GN",
						"value": 216.023
					},
					{
						"key": "WC",
						"value": 78.546
					},
					{
						"key": "WTG",
						"value": 143.674
					},
					{
						"key": "WTV",
						"value": 38.395
					},
					{
						"key": "WB",
						"value": 0.417
					},
					{
						"key": "WN",
						"value": 100
					},
					{
						"key": "QC",
						"value": 3.436
					},
					{
						"key": "QG",
						"value": 7.706
					}
				]
			}
		]
	},
	"WasteDefinition": {
		"wastes": [
			{
				"flow": "QC",
				"type": "EXERGY",
				"recycle": 0,
				"values": [
					{
						"process": "SHT",
						"value": 0.25
					},
					{
						"process": "EVAP",
						"value": 0.45
					},
					{
						"process": "ECON",
						"value": 0.3
					}
				]
			},
			{
				"flow": "QG",
				"type": "IRREVERSIBILITY",
				"recycle": 0,
				"values": [
					{
						"process": "COMB",
						"value": 0.6
					},
					{
						"process": "COMP",
						"value": 0.4
					}
				]
			}
		]
	},
	"ResourcesCost": {
		"Samples": [
			{
				"sampleId": "Base",
				"flows": [
					{
						"key": "GN",
						"value": 22.5
					}
				],
				"processes": [
					{
						"key": "COMP",
						"value": 0.98
					},
					{
						"key": "TGAS",
						"value": 356.19
					},
					{
						"key": "SHT",
						"value": 289.63
					},
					{
						"key": "EVAP",
						"value": 120.83
					},
					{
						"key": "ECON",
						"value": 13.61
					},
					{
						"key": "TVAP",
						"value": 69.23
					},
					{
						"key": "PUMP",
						"value": 35.44
					},
					{
						"key": "ALTN",
						"value": 0.13
					},
					{
						"key": "COND",
						"value": 9.88
					},
					{
						"key": "STCK",
						"value": 5.24
					}
				]
			}
		]
	},
	"Format": {
		"definitions": [
			{
				"key": "EXERGY",
				"width": 11,
				"precision": 3,
				"unit": "(MW)"
			},
			{
				"key": "EXERGY_COST",
				"width": 11,
				"precision": 3,
				"unit": "(MW)"
			},
			{
				"key": "EXERGY_UNIT_COST",
				"width": 11,
				"precision": 4,
				"unit": "(J/J)"
			},
			{
				"key": "GENERALIZED_COST",
				"width": 11,
				"precision": 2,
				"unit": "($/h)"
			},
			{
				"key": "GENERALIZED_UNIT_COST",
				"width": 11,
				"precision": 3,
				"unit": "($/MWh)"
			},
			{
				"key": "DIAGNOSIS",
				"width": 11,
				"precision": 4,
				"unit": "(MW)"
			}
		]
	}
}
