=== ctorrescuadra/TaesLab/Examples/Templates/plant_model.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$ref": "#/definitions/DataModel",
	"definitions": {
		"DataModel": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"ProductiveStructure": {
					"$ref": "#/definitions/ProductiveStructure"
				},
				"ExergyStates": {
					"$ref": "#/definitions/ExergyStates"
				},
				"WasteDefinition": {
					"$ref": "#/definitions/WasteDefinition"
				},
				"ResourcesCost": {
					"$ref": "#/definitions/ResourcesCost"
				},
				"Format": {
					"$ref": "#/definitions/Format"
				}
			},
			"required": [
				"ProductiveStructure",
				"ExergyStates"
			]
		},
		"ProductiveStructure": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"flows": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Flow"
					}
				},
				"processes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Process"
					}
				}
			},
			"required": [
				"flows",
				"processes"
			]
		},
		"Flow": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"type": {
					"type": "string",
					"enum": [
						"INTERNAL",
						"RESOURCE",
						"OUTPUT",
						"WASTE"
					]
				}
			},
			"required": [
				"key",
				"type"
			]
		},
		"Process": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"description": {
					"type": "string"
				},
				"fuel": {
					"type": "string"
				},
				"product": {
					"type": "string"
				},
				"type": {
					"type": "string",
					"enum": [
						"PRODUCTIVE",
						"DISSIPATIVE"
					]
				}
			},
			"required": [
				"key",
				"description",
				"fuel",
				"product",
				"type"
			]
		},
		"ExergyStates": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"States": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/State"
					}
				}
			},
			"required": [
				"States"
			]
		},
		"State": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"stateId": {
					"type": "string"
				},
				"exergy": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				}
			},
			"required": [
				"exergy",
				"stateId"
			]
		},
		"Format": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"definitions": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/FormatDefinition"
					}
				}
			},
			"required": [
				"definitions"
			]
		},
		"FormatDefinition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"type": "string",
					"enum": [
						"EXERGY",
						"EXERGY_COST",
						"EXERGY_UNIT_COST",
						"GENERALIZED_COST",
						"GENERALIZED_UNIT_COST",
						"DIAGNOSIS"
					]
				},
				"width": {
					"type": "integer",
					"minimum": 1
				},
				"precision": {
					"type": "integer",
					"minimum": 0
				},
				"unit": {
					"type": "string"
				}
			},
			"required": [
				"key",
				"precision",
				"unit",
				"width"
			]
		},
		"ResourcesCost": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"Samples": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Sample"
					}
				}
			},
			"required": [
				"Samples"
			]
		},
		"Sample": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"sampleId": {
					"type": "string"
				},
				"flows": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				},
				"processes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				}
			},
			"required": [
				"sampleId",
				"flows"
			]
		},
		"WasteDefinition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"wastes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Wastes"
					}
				}
			},
			"required": [
				"wastes"
			]
		},
		"Wastes": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"flow": {
					"$ref": "#/definitions/Keys"
				},
				"type": {
					"type": "string",
					"enum": [
						"DEFAULT",
						"MANUAL",
						"RESOURCES",
						"EXERGY",
						"COST",
						"IRREVERSIBILITY",
						"HYBRID"
					]
				},
				"recycle": {
					"type": "number",
					"minimum": 0,
					"maximum": 1
				},
				"values": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/WasteAllocation"
					}
				}
			},
			"required": [
				"flow",
				"type"
			]
		},
		"WasteAllocation": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"process": {
					"$ref": "#/definitions/Keys"
				},
				"value": {
					"type": "number",
					"minimum": 0
				}
			},
			"required": [
				"process",
				"value"
			]
		},
		"Values": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"value": {
					"type": "number",
					"minimum": 0
				}
			},
			"required": [
				"key",
				"value"
			]
		},
		"Keys": {
			"type": "string",
			"pattern": "^[A-Z][A-Za-z0-9]+$"
		}
	}
}

=== ctorrescuadra/TaesLab/Examples/rankine/rankine_model.json
{
	"ProductiveStructure": {
		"flows": [
			{
				"key": "CMB",
				"type": "RESOURCE"
			},
			{
				"key": "B2",
				"type": "INTERNAL"
			},
			{
				"key": "B3",
				"type": "INTERNAL"
			},
			{
				"key": "B4",
				"type": "INTERNAL"
			},
			{
				"key": "B5",
				"type": "INTERNAL"
			},
			{
				"key": "WT",
				"type": "INTERNAL"
			},
			{
				"key": "WP",
				"type": "INTERNAL"
			},
			{
				"key": "WC",
				"type": "INTERNAL"
			},
			{
				"key": "WN",
				"type": "OUTPUT"
			},
			{
				"key": "QC",
				"type": "WASTE"
			}
		],
		"processes": [
			{
				"key": "BOIL",
				"description": "Boiler",
				"fuel": "CMB",
				"product": "B2-B5",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TURB",
				"description": "Turbine",
				"fuel": "B2-B3",
				"product": "WT",
				"type": "PRODUCTIVE"
			},
			{
				"key": "PUMP",
				"description": "Pump",
				"fuel": "WP",
				"product": "B5-B4",
				"type": "PRODUCTIVE"
			},
			{
				"key": "GEN",
				"description": "Alternador",
				"fuel": "WT",
				"product": "WN+WP+WC",
				"type": "PRODUCTIVE"
			},
			{
				"key": "COND",
				"description": "Condenser",
				"fuel": "WC+(B3-B4)",
				"product": "QC",
				"type": "DISSIPATIVE"
			}
		]
	},
	"ExergyStates": {
		"States": [
			{
				"stateId": "Reference",
				"exergy": [
					{
						"key": "CMB",
						"value": 34833
					},
					{
						"key": "B2",
						"value": 13362
					},
					{
						"key": "B3",
						"value": 1197
					},
					{
						"key": "B4",
						"value": 22.01
					},
					{
						"key": "B5",
						"value": 121.5
					},
					{
						"key": "WT",
						"value": 10435
					},
					{
						"key": "WP",
						"value": 104.4
					},
					{
						"key": "WC",
						"value": 122.4
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QC",
						"value": 1175
					}
				]
			},
			{
				"stateId": "GEN1",
				"exergy": [
					{
						"key": "CMB",
						"value": 35200
					},
					{
						"key": "B2",
						"value": 13503
					},
					{
						"key": "B3",
						"value": 1210
					},
					{
						"key": "B4",
						"value": 22.24
					},
					{
						"key": "B5",
						"value": 122.7
					},
					{
						"key": "WT",
						"value": 10546
					},
					{
						"key": "WP",
						"value": 105.5
					},
					{
						"key": "WC",
						"value": 123.7
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QC",
						"value": 1187
					}
				]
			},
			{
				"stateId": "TUR83",
				"exergy": [
					{
						"key": "CMB",
						"value": 35683
					},
					{
						"key": "B2",
						"value": 13688
					},
					{
						"key": "B3",
						"value": 1241
					},
					{
						"key": "B4",
						"value": 22.55
					},
					{
						"key": "B5",
						"value": 124.4
					},
					{
						"key": "WT",
						"value": 10439
					},
					{
						"key": "WP",
						"value": 104.4
					},
					{
						"key": "WC",
						"value": 125.4
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QC",
						"value": 1219
					}
				]
			},
			{
				"stateId": "VC9",
				"exergy": [
					{
						"key": "CMB",
						"value": 35389
					},
					{
						"key": "B2",
						"value": 13660
					},
					{
						"key": "B3",
						"value": 1518
					},
					{
						"key": "B4",
						"value": 35.34
					},
					{
						"key": "B5",
						"value": 137.6
					},
					{
						"key": "WT",
						"value": 10439
					},
					{
						"key": "WP",
						"value": 104.4
					},
					{
						"key": "WC",
						"value": 125.3
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QC",
						"value": 1483
					}
				]
			},
			{
				"stateId": "T490",
				"exergy": [
					{
						"key": "CMB",
						"value": 34962
					},
					{
						"key": "B2",
						"value": 13370
					},
					{
						"key": "B3",
						"value": 1204
					},
					{
						"key": "B4",
						"value": 22.27
					},
					{
						"key": "B5",
						"value": 122.9
					},
					{
						"key": "WT",
						"value": 10437
					},
					{
						"key": "WP",
						"value": 104.4
					},
					{
						"key": "WC",
						"value": 123.9
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QC",
						"value": 1182
					}
				]
			},
			{
				"stateId": "B84",
				"exergy": [
					{
						"key": "CMB",
						"value": 35248
					},
					{
						"key": "B2",
						"value": 13362
					},
					{
						"key": "B3",
						"value": 1197
					},
					{
						"key": "B4",
						"value": 22.01
					},
					{
						"key": "B5",
						"value": 121.5
					},
					{
						"key": "WT",
						"value": 10435
					},
					{
						"key": "WP",
						"value": 104.4
					},
					{
						"key": "WC",
						"value": 122.4
					},
					{
						"key": "WN",
						"value": 10000
					},
					{
						"key": "QC",
						"value": 1175
					}
				]
			}
		]
	},
	"WasteDefinition": {
		"wastes": [
			{
				"flow": "QC",
				"type": "MANUAL",
				"recycle": 0,
				"values": [
					{
						"process": "BOIL",
						"value": 0.9
					},
					{
						"process": "TURB",
						"value": 0.1
					}
				]
			}
		]
	},
	"Format": {
		"definitions": [
			{
				"key": "EXERGY",
				"width": 10,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "EXERGY_COST",
				"width": 10,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "EXERGY_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "(J/J)"
			},
			{
				"key": "GENERALIZED_COST",
				"width": 10,
				"precision": 1,
				"unit": "($/h)"
			},
			{
				"key": "GENERALIZED_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "($/kWh)"
			},
			{
				"key": "DIAGNOSIS",
				"width": 10,
				"precision": 3,
				"unit": "(kW)"
			}
		]
	}
}

=== ctorrescuadra/TaesLab/Examples/ccpoly/ccpoly_model.json
{
	"ProductiveStructure": {
		"flows": [
			{
				"key": "G1",
				"type": "RESOURCE"
			},
			{
				"key": "G2",
				"type": "INTERNAL"
			},
			{
				"key": "G3",
				"type": "INTERNAL"
			},
			{
				"key": "G4",
				"type": "INTERNAL"
			},
			{
				"key": "G5",
				"type": "INTERNAL"
			},
			{
				"key": "G6",
				"type": "INTERNAL"
			},
			{
				"key": "G7",
				"type": "INTERNAL"
			},
			{
				"key": "G8",
				"type": "INTERNAL"
			},
			{
				"key": "V1",
				"type": "INTERNAL"
			},
			{
				"key": "V2",
				"type": "INTERNAL"
			},
			{
				"key": "V3",
				"type": "INTERNAL"
			},
			{
				"key": "V4",
				"type": "INTERNAL"
			},
			{
				"key": "WAC",
				"type": "INTERNAL"
			},
			{
				"key": "WGT",
				"type": "INTERNAL"
			},
			{
				"key": "WST",
				"type": "INTERNAL"
			},
			{
				"key": "WCP",
				"type": "INTERNAL"
			},
			{
				"key": "GN",
				"type": "RESOURCE"
			},
			{
				"key": "WN",
				"type": "OUTPUT"
			},
			{
				"key": "COLD",
				"type": "OUTPUT"
			},
			{
				"key": "HEAT",
				"type": "OUTPUT"
			},
			{
				"key": "G9",
				"type": "WASTE"
			},
			{
				"key": "QCON",
				"type": "WASTE"
			}
		],
		"processes": [
			{
				"key": "AC",
				"description": "Air Compressor",
				"fuel": "WAC",
				"product": "G2-G1",
				"type": "PRODUCTIVE"
			},
			{
				"key": "CC",
				"description": "Combustion chamber",
				"fuel": "GN",
				"product": "G3-G2",
				"type": "PRODUCTIVE"
			},
			{
				"key": "GT",
				"description": "Gas Turbine",
				"fuel": "G3-G4-G6",
				"product": "WGT+WAC",
				"type": "PRODUCTIVE"
			},
			{
				"key": "HRSG",
				"description": "HRSG",
				"fuel": "G4-G5",
				"product": "V1-V4",
				"type": "PRODUCTIVE"
			},
			{
				"key": "ST",
				"description": "Steam Turbine",
				"fuel": "V1-V2",
				"product": "WST",
				"type": "PRODUCTIVE"
			},
			{
				"key": "CP",
				"description": "Condenser pump",
				"fuel": "WCP",
				"product": "V4-V3",
				"type": "PRODUCTIVE"
			},
			{
				"key": "GEN",
				"description": "Generator",
				"fuel": "WGT+WST",
				"product": "WN+WCP",
				"type": "PRODUCTIVE"
			},
			{
				"key": "REF",
				"description": "Refrigerator",
				"fuel": "G6-G7",
				"product": "COLD",
				"type": "PRODUCTIVE"
			},
			{
				"key": "HE",
				"description": "Heater",
				"fuel": "G7-G8",
				"product": "HEAT",
				"type": "PRODUCTIVE"
			},
			{
				"key": "STCK",
				"description": "Stack",
				"fuel": "G5+G8",
				"product": "G9",
				"type": "DISSIPATIVE"
			},
			{
				"key": "CND",
				"description": "Condenser",
				"fuel": "V2-V3",
				"product": "QCON",
				"type": "DISSIPATIVE"
			}
		]
	},
	"ExergyStates": {
		"States": [
			{
				"stateId": "Reference",
				"exergy": [
					{
						"key": "G1",
						"value": 0
					},
					{
						"key": "G2",
						"value": 251434.739778
					},
					{
						"key": "G3",
						"value": 800981.435528
					},
					{
						"key": "G4",
						"value": 238347.475611
					},
					{
						"key": "G5",
						"value": 17248.722222
					},
					{
						"key": "G6",
						"value": 2973.558
					},
					{
						"key": "G7",
						"value": 467.4062
					},
					{
						"key": "G8",
						"value": 241.364
					},
					{
						"key": "V1",
						"value": 170942.394444
					},
					{
						"key": "V2",
						"value": 14770.366667
					},
					{
						"key": "V3",
						"value": 18.433333
					},
					{
						"key": "V4",
						"value": 257.956944
					},
					{
						"key": "WAC",
						"value": 261432.5
					},
					{
						"key": "WGT",
						"value": 256695.1
					},
					{
						"key": "WST",
						"value": 141167.47
					},
					{
						"key": "WCP",
						"value": 384.03
					},
					{
						"key": "GN",
						"value": 718204.1
					},
					{
						"key": "WN",
						"value": 389521.2886
					},
					{
						"key": "COLD",
						"value": 500.991
					},
					{
						"key": "HEAT",
						"value": 91.361025
					},
					{
						"key": "G9",
						"value": 17490.086222
					},
					{
						"key": "QCON",
						"value": 14751.933333
					}
				]
			}
		]
	},
	"WasteDefinition": {
		"wastes": [
			{
				"flow": "G9",
				"type": "MANUAL",
				"recycle": 0,
				"values": [
					{
						"process": "CC",
						"value": 1
					}
				]
			},
			{
				"flow": "QCON",
				"type": "MANUAL",
				"recycle": 0,
				"values": [
					{
						"process": "HRSG",
						"value": 1
					}
				]
			}
		]
	},
	"Format": {
		"definitions": [
			{
				"key": "EXERGY",
				"width": 11,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "EXERGY_COST",
				"width": 11,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "EXERGY_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "(J/J)"
			},
			{
				"key": "GENERALIZED_COST",
				"width": 10,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "GENERALIZED_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "(J/J)"
			},
			{
				"key": "DIAGNOSIS",
				"width": 11,
				"precision": 2,
				"unit": "(kW)"
			}
		]
	}
}

=== ctorrescuadra/TaesLab/Examples/ccplant/ccplant_model.json
{
	"ProductiveStructure": {
		"flows": [
			{
				"key": "A1",
				"type": "INTERNAL"
			},
			{
				"key": "A2",
				"type": "INTERNAL"
			},
			{
				"key": "A3",
				"type": "INTERNAL"
			},
			{
				"key": "A4",
				"type": "INTERNAL"
			},
			{
				"key": "V5",
				"type": "INTERNAL"
			},
			{
				"key": "V6",
				"type": "INTERNAL"
			},
			{
				"key": "V7",
				"type": "INTERNAL"
			},
			{
				"key": "V8",
				"type": "INTERNAL"
			},
			{
				"key": "GN",
				"type": "RESOURCE"
			},
			{
				"key": "WC",
				"type": "INTERNAL"
			},
			{
				"key": "WTG",
				"type": "INTERNAL"
			},
			{
				"key": "WTV",
				"type": "INTERNAL"
			},
			{
				"key": "WB",
				"type": "INTERNAL"
			},
			{
				"key": "WN",
				"type": "OUTPUT"
			},
			{
				"key": "QG",
				"type": "WASTE"
			},
			{
				"key": "QC",
				"type": "WASTE"
			}
		],
		"processes": [
			{
				"key": "COMB",
				"description": "Combustor",
				"fuel": "GN",
				"product": "A2-A1",
				"type": "PRODUCTIVE"
			},
			{
				"key": "COMP",
				"description": "Compresor",
				"fuel": "WC",
				"product": "A1",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TGAS",
				"description": "Turbina Gas",
				"fuel": "A2-A3",
				"product": "WTG+WC",
				"type": "PRODUCTIVE"
			},
			{
				"key": "HRSG",
				"description": "HRSG",
				"fuel": "A3-A4",
				"product": "V6-V5",
				"type": "PRODUCTIVE"
			},
			{
				"key": "TVAP",
				"description": "Turbina de vapor",
				"fuel": "V6-V7",
				"product": "WTV",
				"type": "PRODUCTIVE"
			},
			{
				"key": "PUMP",
				"description": "Bomba alimentacion",
				"fuel": "WB",
				"product": "V5-V8",
				"type": "PRODUCTIVE"
			},
			{
				"key": "ALTN",
				"description": "Alternador",
				"fuel": "WTG+WTV",
				"product": "WB+WN",
				"type": "PRODUCTIVE"
			},
			{
				"key": "STCK",
				"description": "Chimenea",
				"fuel": "A4",
				"product": "QG",
				"type": "DISSIPATIVE"
			},
			{
				"key": "COND",
				"description": "Condensador",
				"fuel": "V7-V8",
				"product": "QC",
				"type": "DISSIPATIVE"
			}
		]
	},
	"ExergyStates": {
		"States": [
			{
				"stateId": "Reference",
				"exergy": [
					{
						"key": "A1",
						"value": 71507
					},
					{
						"key": "A2",
						"value": 216960
					},
					{
						"key": "A3",
						"value": 69697
					},
					{
						"key": "A4",
						"value": 7775
					},
					{
						"key": "V5",
						"value": 438.5
					},
					{
						"key": "V6",
						"value": 52447
					},
					{
						"key": "V7",
						"value": 4050
					},
					{
						"key": "V8",
						"value": 63.1
					},
					{
						"key": "GN",
						"value": 223624
					},
					{
						"key": "WC",
						"value": 77290
					},
					{
						"key": "WTG",
						"value": 61022
					},
					{
						"key": "WTV",
						"value": 41465
					},
					{
						"key": "WB",
						"value": 437.5
					},
					{
						"key": "WN",
						"value": 100000
					},
					{
						"key": "QG",
						"value": 7775
					},
					{
						"key": "QC",
						"value": 3986.9
					}
				]
			},
			{
				"stateId": "TG1",
				"exergy": [
					{
						"key": "A1",
						"value": 72653
					},
					{
						"key": "A2",
						"value": 218948
					},
					{
						"key": "A3",
						"value": 70336
					},
					{
						"key": "A4",
						"value": 7846
					},
					{
						"key": "V5",
						"value": 442.6
					},
					{
						"key": "V6",
						"value": 52927
					},
					{
						"key": "V7",
						"value": 4087
					},
					{
						"key": "V8",
						"value": 63.68
					},
					{
						"key": "GN",
						"value": 224719
					},
					{
						"key": "WC",
						"value": 78933
					},
					{
						"key": "WTG",
						"value": 60647
					},
					{
						"key": "WTV",
						"value": 41845
					},
					{
						"key": "WB",
						"value": 441.5
					},
					{
						"key": "WN",
						"value": 100000
					},
					{
						"key": "QG",
						"value": 7846
					},
					{
						"key": "QC",
						"value": 4023.32
					}
				]
			},
			{
				"stateId": "TV1",
				"exergy": [
					{
						"key": "A1",
						"value": 71850
					},
					{
						"key": "A2",
						"value": 218002
					},
					{
						"key": "A3",
						"value": 70032
					},
					{
						"key": "A4",
						"value": 7812
					},
					{
						"key": "V5",
						"value": 440.7
					},
					{
						"key": "V6",
						"value": 52699
					},
					{
						"key": "V7",
						"value": 4096
					},
					{
						"key": "V8",
						"value": 63.4
					},
					{
						"key": "GN",
						"value": 224698
					},
					{
						"key": "WC",
						"value": 77661
					},
					{
						"key": "WTG",
						"value": 61315
					},
					{
						"key": "WTV",
						"value": 41174
					},
					{
						"key": "WB",
						"value": 439.6
					},
					{
						"key": "WN",
						"value": 100000
					},
					{
						"key": "QG",
						"value": 7812
					},
					{
						"key": "QC",
						"value": 4032.6
					}
				]
			},
			{
				"stateId": "ALT2",
				"exergy": [
					{
						"key": "A1",
						"value": 72247
					},
					{
						"key": "A2",
						"value": 219207
					},
					{
						"key": "A3",
						"value": 70419
					},
					{
						"key": "A4",
						"value": 7855
					},
					{
						"key": "V5",
						"value": 443.1
					},
					{
						"key": "V6",
						"value": 52990
					},
					{
						"key": "V7",
						"value": 4092
					},
					{
						"key": "V8",
						"value": 63.75
					},
					{
						"key": "GN",
						"value": 225940
					},
					{
						"key": "WC",
						"value": 78091
					},
					{
						"key": "WTG",
						"value": 61654
					},
					{
						"key": "WTV",
						"value": 41894
					},
					{
						"key": "WB",
						"value": 442
					},
					{
						"key": "WN",
						"value": 100000
					},
					{
						"key": "QG",
						"value": 7855
					},
					{
						"key": "QC",
						"value": 4028.25
					}
				]
			},
			{
				"stateId": "Prueba",
				"exergy": [
					{
						"key": "A1",
						"value": 68818
					},
					{
						"key": "A2",
						"value": 203917
					},
					{
						"key": "A3",
						"value": 66513
					},
					{
						"key": "A4",
						"value": 6552
					},
					{
						"key": "V5",
						"value": 234.8
					},
					{
						"key": "V6",
						"value": 48646
					},
					{
						"key": "V7",
						"value": 4882
					},
					{
						"key": "V8",
						"value": 84.63
					},
					{
						"key": "GN",
						"value": 210706
					},
					{
						"key": "WC",
						"value": 74441
					},
					{
						"key": "WTG",
						"value": 54470
					},
					{
						"key": "WTV",
						"value": 37545
					},
					{
						"key": "WB",
						"value": 174.7
					},
					{
						"key": "WN",
						"value": 90000
					},
					{
						"key": "QG",
						"value": 6552
					},
					{
						"key": "QC",
						"value": 4760
					}
				]
			}
		]
	},
	"WasteDefinition": {
		"wastes": [
			{
				"flow": "QG",
				"type": "MANUAL",
				"recycle": 0,
				"values": [
					{
						"process": "COMB",
						"value": 1
					}
				]
			},
			{
				"flow": "QC",
				"type": "MANUAL",
				"recycle": 0,
				"values": [
					{
						"process": "HRSG",
						"value": 1
					}
				]
			}
		]
	},
	"ResourcesCost": {
		"Samples": [
			{
				"sampleId": "Base",
				"flows": [
					{
						"key": "GN",
						"value": 1.32
					}
				],
				"processes": [
					{
						"key": "COMB",
						"value": 58.8
					},
					{
						"key": "COMP",
						"value": 21371.4
					},
					{
						"key": "TGAS",
						"value": 17377.8
					},
					{
						"key": "HRSG",
						"value": 12220.2
					},
					{
						"key": "TVAP",
						"value": 2126.4
					},
					{
						"key": "PUMP",
						"value": 7.8
					},
					{
						"key": "ALTN",
						"value": 592.8
					},
					{
						"key": "COND",
						"value": 314.4
					},
					{
						"key": "STCK",
						"value": 25.2
					}
				]
			}
		]
	},
	"Format": {
		"definitions": [
			{
				"key": "EXERGY",
				"width": 11,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "EXERGY_COST",
				"width": 11,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "EXERGY_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "(J/J)"
			},
			{
				"key": "GENERALIZED_COST",
				"width": 10,
				"precision": 1,
				"unit": "(kW)"
			},
			{
				"key": "GENERALIZED_UNIT_COST",
				"width": 10,
				"precision": 4,
				"unit": "(J/J)"
			},
			{
				"key": "DIAGNOSIS",
				"width": 11,
				"precision": 2,
				"unit": "(kW)"
			}
		]
	}
}
