=== ctorrescuadra/TaesLab/Config/plant_model.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$ref": "#/definitions/DataModel",
	"definitions": {
		"DataModel": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"ProductiveStructure": {
					"$ref": "#/definitions/ProductiveStructure"
				},
				"ExergyStates": {
					"$ref": "#/definitions/ExergyStates"
				},
				"WasteDefinition": {
					"$ref": "#/definitions/WasteDefinition"
				},
				"ResourcesCost": {
					"$ref": "#/definitions/ResourcesCost"
				},
				"Format": {
					"$ref": "#/definitions/Format"
				}
			},
			"required": [
				"ProductiveStructure",
				"ExergyStates"
			],
			"title": "DataModel",
			"description": "TaesLab plant data model structure"
		},
		"ProductiveStructure": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"name": {
					"$ref": "#/definitions/Text"
				},
				"flows": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Flow"
					}
				},
				"processes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Process"
					}
				}
			},
			"required": [
				"flows",
				"processes"
			],
			"title": "ProductiveStructure",
			"description": "Productive structure of the plant"	
		},
		"Flow": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"type": {
					"type": "string",
					"enum": [
						"INTERNAL",
						"RESOURCE",
						"OUTPUT",
						"WASTE"
					]
				},
				"description": {
					"$ref": "#/definitions/Text"
				}
			},
			"required": [
				"key",
				"type"
			],
			"title": "Flow",
			"description": "Definition of a flow in the productive structure"
		},
		"Process": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"description": {
					"$ref": "#/definitions/Text"
				},
				"fuel": {
					"$ref": "#/definitions/Text"
				},
				"product": {
					"$ref": "#/definitions/Text"
				},
				"type": {
					"type": "string",
					"enum": [
						"PRODUCTIVE",
						"DISSIPATIVE"
					]
				}
			},
			"required": [
				"key",
				"fuel",
				"product",
				"type"
			],
			"title": "Process",
			"description": "Definition of a process in the productive structure"
		},
		"ExergyStates": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"States": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/State"
					}
				}
			},
			"required": [
				"States"
			],
			"title": "ExergyStates",
			"description": "Collection of exergy states used in the plant model"
		},
		"State": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"stateId": {
					"$ref": "#/definitions/Names"
				},
				"exergy": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				}
			},
			"required": [
				"exergy",
				"stateId"
			],
			"title": "State",
			"description": "Exergy state definition"	
		},
		"Format": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"definitions": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/FormatDefinition"
					}
				}
			},
			"required": [
				"definitions"
			],
			"title": "Format",
			"description": "Format definitions for displaying data"
		},
		"FormatDefinition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"type": "string",
					"enum": [
						"EXERGY",
						"EXERGY_COST",
						"EXERGY_UNIT_COST",
						"GENERALIZED_COST",
						"GENERALIZED_UNIT_COST",
						"DIAGNOSIS",
						"GENERALIZED_DIAGNOSIS"
					]
				},
				"width": {
					"type": "integer",
					"minimum": 1
				},
				"precision": {
					"type": "integer",
					"minimum": 0
				},
				"unit": {
					"$ref": "#/definitions/Text"
				}
			},
			"required": [
				"key",
				"precision",
				"unit",
				"width"
			],
			"title": "FormatDefinition",
			"description": "Definition of a specific format for data display"
		},
		"ResourcesCost": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"Samples": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Sample"
					}
				}
			},
			"required": [
				"Samples"
			],
			"title": "ResourcesCost",
			"description": "Resource cost definitions for different samples"
		},
		"Sample": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"sampleId": {
					"$ref": "#/definitions/Names"
				},
				"flows": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				},
				"processes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Values"
					}
				}
			},
			"required": [
				"sampleId",
				"flows"
			],
			"title": "Sample",
			"description": "Sample data for resource costs"
		},
		"WasteDefinition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"wastes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Wastes"
					}
				}
			},
			"required": [
				"wastes"
			],
			"title": "WasteDefinition",
			"description": "Definition of waste allocations in the plant model"
		},
		"Wastes": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"flow": {
					"$ref": "#/definitions/Keys"
				},
				"type": {
					"type": "string",
					"enum": [
						"DEFAULT",
						"MANUAL",
						"RESOURCES",
						"EXERGY",
						"COST",
						"IRREVERSIBILITY",
						"HYBRID"
					]
				},
				"recycle": {
					"type": "number",
					"minimum": 0,
					"maximum": 1
				},
				"values": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/WasteAllocation"
					}
				}
			},
			"required": [
				"flow",
				"type"
			],
			"title": "Wastes",
			"description": "Definition of wastes in the plant model"
		},
		"WasteAllocation": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"process": {
					"$ref": "#/definitions/Keys"
				},
				"value": {
					"type": "number",
					"minimum": 0
				}
			},
			"required": [
				"process",
				"value"
			],
			"title": "WasteAllocation",
			"description": "Allocation of waste to a specific process"
		},
		"Values": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key": {
					"$ref": "#/definitions/Keys"
				},
				"value": {
					"type": "number",
					"minimum": 0
				}
			},
			"required": [
				"key",
				"value"
			],
			"title": "Values",
			"description": "Key-value pairs representing values in the plant model"
		},
		"Keys": {
			"type": "string",
			"pattern": "^[A-Z][A-Za-z0-9]{1,7}$",
			"description": "Identifier key for flows and processes"
		},
		"Names": {
			"type": "string",
			"pattern": "^[A-Za-z]\\w{1,9}$",
			"description": "Name identifier for samples"
		},
		"Text": {
            "type": "string",
            "minLength": 2,
			"description": "Textual data with a minimum length of 2 characters"
        }
	}
}

=== ctorrescuadra/TaesLab/Examples/bfgt/bfgt0_model.json
{
  "Format": {
    "definitions": [
      {
        "key": "EXERGY",
        "width": 10,
        "precision": 1,
        "unit": "(kW)"
      },
      {
        "key": "EXERGY_COST",
        "width": 10,
        "precision": 1,
        "unit": "(kW)"
      },
      {
        "key": "EXERGY_UNIT_COST",
        "width": 10,
        "precision": 4,
        "unit": "(J/J)"
      },
      {
        "key": "GENERALIZED_COST",
        "width": 10,
        "precision": 2,
        "unit": "(c/h)"
      },
      {
        "key": "GENERALIZED_UNIT_COST",
        "width": 10,
        "precision": 4,
        "unit": "(c/kWh)"
      },
      {
        "key": "DIAGNOSIS",
        "width": 10,
        "precision": 2,
        "unit": "(kW)"
      }
    ]
  },
  "ProductiveStructure": {
    "flows": [
      {
        "key": "B1",
        "type": "RESOURCE"
      },
      {
        "key": "B2",
        "type": "RESOURCE"
      },
      {
        "key": "B3",
        "type": "INTERNAL"
      },
      {
        "key": "B4",
        "type": "INTERNAL"
      },
      {
        "key": "B5",
        "type": "INTERNAL"
      },
      {
        "key": "B6",
        "type": "INTERNAL"
      },
      {
        "key": "B7",
        "type": "INTERNAL"
      },
      {
        "key": "B9",
        "type": "INTERNAL"
      },
      {
        "key": "B10",
        "type": "INTERNAL"
      },
      {
        "key": "B11",
        "type": "INTERNAL"
      },
      {
        "key": "B12",
        "type": "INTERNAL"
      },
      {
        "key": "WGC",
        "type": "INTERNAL"
      },
      {
        "key": "WAC",
        "type": "INTERNAL"
      },
      {
        "key": "WN",
        "type": "OUTPUT"
      },
      {
        "key": "QG",
        "type": "WASTE"
      }
    ],
    "processes": [
      {
        "key": "CC",
        "type": "PRODUCTIVE",
        "fuel": "B5+B6",
        "product": "B7"
      },
      {
        "key": "GC",
        "type": "PRODUCTIVE",
        "fuel": "WGC",
        "product": "B4-B2"
      },
      {
        "key": "AC",
        "type": "PRODUCTIVE",
        "fuel": "WAC",
        "product": "B3-B1"
      },
      {
        "key": "GHE",
        "type": "PRODUCTIVE",
        "fuel": "B10-B12",
        "product": "B6-B4"
      },
      {
        "key": "AHE",
        "type": "PRODUCTIVE",
        "fuel": "B9-B11",
        "product": "B5-B3"
      },
      {
        "key": "TRB",
        "type": "PRODUCTIVE",
        "fuel": "B7-B9-B10",
        "product": "WN+WGC+WAC"
      },
      {
        "key": "STCK",
        "type": "DISSIPATIVE",
        "fuel": "B11+B12",
        "product": "QG"
      }
    ]
  },
  "ExergyStates": {
    "States": [{
      "stateId": "Reference",
      "exergy": [
        {
          "key": "B1",
          "value": 0
        },
        {
          "key": "B2",
          "value": 12077.294685990339
        },
        {
          "key": "B3",
          "value": 4995.1690821256043
        },
        {
          "key": "B4",
          "value": 12643.719806763285
        },
        {
          "key": "B5",
          "value": 8113.5265700483105
        },
        {
          "key": "B6",
          "value": 13004.830917874397
        },
        {
          "key": "B7",
          "value": 16925.120772946859
        },
        {
          "key": "B9",
          "value": 6246.376811594203
        },
        {
          "key": "B10",
          "value": 727.05314009661834
        },
        {
          "key": "B11",
          "value": 2387.68115942029
        },
        {
          "key": "B12",
          "value": 277.77777777777777
        },
        {
          "key": "WGC",
          "value": 650.96618357487921
        },
        {
          "key": "WAC",
          "value": 5602.6570048309177
        },
        {
          "key": "WN",
          "value": 3000
        },
        {
          "key": "QG",
          "value": 2665.4589371980678
        }
    ]}
    ]
  },
  "WasteDefinition": {
    "wastes": [{
      "flow": "QG",
      "type": "MANUAL",
      "recycle": 0.6,
      "values": [{
        "process": "CC",
        "value": 1
      }
    ]
  }]
  }
}
