=== ctorrescuadra/TaesLab/Examples/plant_model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ProductiveStructure">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="flows" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="key" type="keyname"/>
                                        <xs:element name="type" type="flowType" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="processes" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="key" type="keyname" />
                                        <xs:element name="description" type="xs:string" />
                                        <xs:element name="fuel" type="xs:string" />
                                        <xs:element name="product" type="xs:string" />
                                        <xs:element name="type" type="productType" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ExergyStates">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="States" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="exergy" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="key" type="keyname" />
                                                    <xs:element name="value" type="positiveDecimal" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="state" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="WasteDefinition" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="wastes" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="flow" type="keyname" />
                                        <xs:element name="type" type="wasteAllocation" />
                                        <xs:element name="recycle" minOccurs="0" type="boundedDecimal" />
                                        <xs:element name="values" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="process" type="keyname" />
                                                    <xs:element name="value" type="positiveDecimal" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ResourcesCost" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Samples" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="flows" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="key" type="keyname" />
                                                    <xs:element name="value" type="positiveDecimal" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="processes" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="key" type="keyname" />
                                                    <xs:element name="value" type="positiveDecimal" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="sample" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Format" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="definitions" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="key" type="formatType" />
                                        <xs:element name="width" type="xs:positiveInteger" />
                                        <xs:element name="precision" type="xs:nonNegativeInteger" />
                                        <xs:element name="unit" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="keyname">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Za-z0-9]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="positiveDecimal">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="boundedDecimal">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="wasteAllocation">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DEFAULT"/>
            <xs:enumeration value="MANUAL"/>
            <xs:enumeration value="RESOURCES"/>
            <xs:enumeration value="EXERGY"/>
            <xs:enumeration value="COST"/>
            <xs:enumeration value="IRREVERSIBILITY"/>
            <xs:enumeration value="HYBRID"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="flowType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="INTERNAL"/>
            <xs:enumeration value="RESOURCE"/>
            <xs:enumeration value="OUTPUT"/>
            <xs:enumeration value="WASTE"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="productType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PRODUCTIVE"/>
            <xs:enumeration value="DISSIPATIVE"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="formatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="EXERGY"/>
            <xs:enumeration value="EXERGY_COST"/>
            <xs:enumeration value="EXERGY_UNIT_COST"/>
            <xs:enumeration value="GENERALIZED_COST"/>
            <xs:enumeration value="GENERALIZED_UNIT_COST"/>
            <xs:enumeration value="DIAGNOSIS"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ctorrescuadra/TaesLab/Examples/polygen/polygen_model.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../plant_model.xsd">
    <ProductiveStructure>
        <flows>
            <key>B1</key>
            <type>RESOURCE</type>
        </flows>
        <flows>
            <key>B2</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B3</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B4</key>
            <type>RESOURCE</type>
        </flows>
        <flows>
            <key>B5</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B6</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B7</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B8</key>
            <type>OUTPUT</type>
        </flows>
        <flows>
            <key>B9</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B10</key>
            <type>RESOURCE</type>
        </flows>
        <flows>
            <key>B11</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B12</key>
            <type>OUTPUT</type>
        </flows>
        <flows>
            <key>B13</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B14</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B15</key>
            <type>RESOURCE</type>
        </flows>
        <flows>
            <key>B16</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B17</key>
            <type>OUTPUT</type>
        </flows>
        <flows>
            <key>B18</key>
            <type>OUTPUT</type>
        </flows>
        <flows>
            <key>B19</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B20</key>
            <type>WASTE</type>
        </flows>
        <processes>
            <key>COMB</key>
            <description>Combustor</description>
            <fuel>B4</fuel>
            <product>B5-B3</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>REGE</key>
            <description>Regenerator</description>
            <fuel>B6-B9</fuel>
            <product>B3-B2</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>COMP</key>
            <description>Compressor</description>
            <fuel>B7</fuel>
            <product>B2-B1</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>TURB</key>
            <description>Turbine</description>
            <fuel>B5-B6</fuel>
            <product>B7+B8</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>ICE</key>
            <description>ICE</description>
            <fuel>B10</fuel>
            <product>B11+B12+(B13-B14)</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>WHTR</key>
            <description>Water Heater</description>
            <fuel>B13-B14</fuel>
            <product>B17</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>BURN</key>
            <description>Burner</description>
            <fuel>B15</fuel>
            <product>B16-B11</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>HRSG</key>
            <description>HRSG</description>
            <fuel>B16+B9-B19</fuel>
            <product>B18</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>STCK</key>
            <description>Stack</description>
            <fuel>B19</fuel>
            <product>B20</product>
            <type>DISSIPATIVE</type>
        </processes>
    </ProductiveStructure>
    <ExergyStates>
        <States state="Reference">
            <exergy>
                <key>B1</key>
                <value>0</value>
            </exergy>
            <exergy>
                <key>B2</key>
                <value>26204</value>
            </exergy>
            <exergy>
                <key>B3</key>
                <value>41732</value>
            </exergy>
            <exergy>
                <key>B4</key>
                <value>78643</value>
            </exergy>
            <exergy>
                <key>B5</key>
                <value>94210</value>
            </exergy>
            <exergy>
                <key>B6</key>
                <value>33696</value>
            </exergy>
            <exergy>
                <key>B7</key>
                <value>27939</value>
            </exergy>
            <exergy>
                <key>B8</key>
                <value>30000</value>
            </exergy>
            <exergy>
                <key>B9</key>
                <value>16271</value>
            </exergy>
            <exergy>
                <key>B10</key>
                <value>27568</value>
            </exergy>
            <exergy>
                <key>B11</key>
                <value>3949</value>
            </exergy>
            <exergy>
                <key>B12</key>
                <value>10000</value>
            </exergy>
            <exergy>
                <key>B13</key>
                <value>3116</value>
            </exergy>
            <exergy>
                <key>B14</key>
                <value>2357</value>
            </exergy>
            <exergy>
                <key>B15</key>
                <value>10717</value>
            </exergy>
            <exergy>
                <key>B16</key>
                <value>10073</value>
            </exergy>
            <exergy>
                <key>B17</key>
                <value>375</value>
            </exergy>
            <exergy>
                <key>B18</key>
                <value>14060</value>
            </exergy>
            <exergy>
                <key>B19</key>
                <value>4129</value>
            </exergy>
            <exergy>
                <key>B20</key>
                <value>4129</value>
            </exergy>
        </States>
    </ExergyStates>
    <WasteDefinition>
        <wastes>
            <flow>B20</flow>
            <type>DEFAULT</type>
            <recycle>0</recycle>
        </wastes>
    </WasteDefinition>
    <ResourcesCost>
        <Samples sample="Base">
            <flows>
                <key>B4</key>
                <value>1.284</value>
            </flows>
            <flows>
                <key>B10</key>
                <value>1.475</value>
            </flows>
            <flows>
                <key>B15</key>
                <value>1.346</value>
            </flows>
        </Samples>
    </ResourcesCost>
</root>

=== ctorrescuadra/TaesLab/Examples/rvpc/rvpc_model.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../plant_model.xsd">
    <ProductiveStructure>
        <flows>
            <key>B1</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B2</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B3</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B4</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B5</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B6</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B7</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>AIR</key>
            <type>RESOURCE</type>
        </flows>
        <flows>
            <key>WT</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>WBC</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>WBA</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>COMB</key>
            <type>RESOURCE</type>
        </flows>
        <flows>
            <key>WN</key>
            <type>OUTPUT</type>
        </flows>
        <flows>
            <key>QCON</key>
            <type>WASTE</type>
        </flows>
        <processes>
            <key>CALD</key>
            <description>Caldera</description>
            <fuel>COMB+AIR</fuel>
            <product>B1-B7</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>TURB</key>
            <description>Turbina</description>
            <fuel>B1-B2-B3</fuel>
            <product>WT</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>BC</key>
            <description>Bomba Condensados</description>
            <fuel>WBC</fuel>
            <product>B5-B4</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>DESG</key>
            <description>Desgasificador</description>
            <fuel>B2+B5</fuel>
            <product>B6</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>BA</key>
            <description>Bomba Alimentacion</description>
            <fuel>WBA</fuel>
            <product>B7-B6</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>GEN</key>
            <description>Generador</description>
            <fuel>WT</fuel>
            <product>WN+WBC+WBA</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>COND</key>
            <description>Condensador</description>
            <fuel>B3-B4</fuel>
            <product>QCON</product>
            <type>DISSIPATIVE</type>
        </processes>
    </ProductiveStructure>
    <ExergyStates>
        <States state="Reference">
            <exergy>
                <key>B1</key>
                <value>146374</value>
            </exergy>
            <exergy>
                <key>B2</key>
                <value>16956</value>
            </exergy>
            <exergy>
                <key>B3</key>
                <value>12183</value>
            </exergy>
            <exergy>
                <key>B4</key>
                <value>256.9</value>
            </exergy>
            <exergy>
                <key>B5</key>
                <value>315.6</value>
            </exergy>
            <exergy>
                <key>B6</key>
                <value>12147</value>
            </exergy>
            <exergy>
                <key>B7</key>
                <value>12993</value>
            </exergy>
            <exergy>
                <key>AIR</key>
                <value>0</value>
            </exergy>
            <exergy>
                <key>WT</key>
                <value>102964</value>
            </exergy>
            <exergy>
                <key>WBC</key>
                <value>58.7</value>
            </exergy>
            <exergy>
                <key>WBA</key>
                <value>846</value>
            </exergy>
            <exergy>
                <key>COMB</key>
                <value>325246</value>
            </exergy>
            <exergy>
                <key>WN</key>
                <value>100000</value>
            </exergy>
            <exergy>
                <key>QCON</key>
                <value>11926.1</value>
            </exergy>
        </States>
        <States state="PC10">
            <exergy>
                <key>B1</key>
                <value>146459</value>
            </exergy>
            <exergy>
                <key>B2</key>
                <value>16966</value>
            </exergy>
            <exergy>
                <key>B3</key>
                <value>12190</value>
            </exergy>
            <exergy>
                <key>B4</key>
                <value>257.1</value>
            </exergy>
            <exergy>
                <key>B5</key>
                <value>315.8</value>
            </exergy>
            <exergy>
                <key>B6</key>
                <value>12154</value>
            </exergy>
            <exergy>
                <key>B7</key>
                <value>13059</value>
            </exergy>
            <exergy>
                <key>AIR</key>
                <value>0</value>
            </exergy>
            <exergy>
                <key>WT</key>
                <value>103024</value>
            </exergy>
            <exergy>
                <key>WBC</key>
                <value>58.8</value>
            </exergy>
            <exergy>
                <key>WBA</key>
                <value>910</value>
            </exergy>
            <exergy>
                <key>COMB</key>
                <value>325366</value>
            </exergy>
            <exergy>
                <key>WN</key>
                <value>100000</value>
            </exergy>
            <exergy>
                <key>QCON</key>
                <value>11932.9</value>
            </exergy>
        </States>
        <States state="T84">
            <exergy>
                <key>B1</key>
                <value>147886</value>
            </exergy>
            <exergy>
                <key>B2</key>
                <value>17139</value>
            </exergy>
            <exergy>
                <key>B3</key>
                <value>12381</value>
            </exergy>
            <exergy>
                <key>B4</key>
                <value>259.7</value>
            </exergy>
            <exergy>
                <key>B5</key>
                <value>319</value>
            </exergy>
            <exergy>
                <key>B6</key>
                <value>12273</value>
            </exergy>
            <exergy>
                <key>B7</key>
                <value>13128</value>
            </exergy>
            <exergy>
                <key>AIR</key>
                <value>0</value>
            </exergy>
            <exergy>
                <key>WT</key>
                <value>102973</value>
            </exergy>
            <exergy>
                <key>WBC</key>
                <value>60</value>
            </exergy>
            <exergy>
                <key>WBA</key>
                <value>860</value>
            </exergy>
            <exergy>
                <key>COMB</key>
                <value>328605</value>
            </exergy>
            <exergy>
                <key>WN</key>
                <value>100000</value>
            </exergy>
            <exergy>
                <key>QCON</key>
                <value>12121.3</value>
            </exergy>
        </States>
    </ExergyStates>
    <WasteDefinition>
        <wastes>
            <flow>QCON</flow>
            <type>MANUAL</type>
            <recycle>0</recycle>
            <values>
                <process>CALD</process>
                <value>0.92</value>
            </values>
            <values>
                <process>DESG</process>
                <value>0.08</value>
            </values>
        </wastes>
    </WasteDefinition>
    <Format>
        <definitions>
            <key>EXERGY</key>
            <width>10</width>
            <precision>1</precision>
            <unit>[kW]</unit>
        </definitions>
        <definitions>
            <key>EXERGY_COST</key>
            <width>10</width>
            <precision>1</precision>
            <unit>[kW]</unit>
        </definitions>
        <definitions>
            <key>EXERGY_UNIT_COST</key>
            <width>10</width>
            <precision>4</precision>
            <unit>[J/J]</unit>
        </definitions>
        <definitions>
            <key>GENERALIZED_COST</key>
            <width>10</width>
            <precision>1</precision>
            <unit>[kW]</unit>
        </definitions>
        <definitions>
            <key>GENERALIZED_UNIT_COST</key>
            <width>10</width>
            <precision>4</precision>
            <unit>[J/J]</unit>
        </definitions>
        <definitions>
            <key>DIAGNOSIS</key>
            <width>10</width>
            <precision>2</precision>
            <unit>[kW]</unit>
        </definitions>
    </Format>
</root>
