=== ctorrescuadra/TaesLab/Examples/plant_model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ProductiveStructure">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="flows" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="key" type="keyname"/>
                                        <xs:element name="type" type="flowType" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="processes" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="key" type="keyname" />
                                        <xs:element name="description" type="xs:string" />
                                        <xs:element name="fuel" type="xs:string" />
                                        <xs:element name="product" type="xs:string" />
                                        <xs:element name="type" type="productType" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ExergyStates">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="States" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="exergy" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="key" type="keyname" />
                                                    <xs:element name="value" type="positiveDecimal" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="state" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="WasteDefinition" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="wastes" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="flow" type="keyname" />
                                        <xs:element name="type" type="wasteAllocation" />
                                        <xs:element name="recycle" minOccurs="0" type="boundedDecimal" />
                                        <xs:element name="values" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="process" type="keyname" />
                                                    <xs:element name="value" type="positiveDecimal" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ResourcesCost" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Samples" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="flows" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="key" type="keyname" />
                                                    <xs:element name="value" type="positiveDecimal" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="processes" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="key" type="keyname" />
                                                    <xs:element name="value" type="positiveDecimal" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="sample" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Format" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="definitions" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="key" type="formatType" />
                                        <xs:element name="width" type="xs:positiveInteger" />
                                        <xs:element name="precision" type="xs:nonNegativeInteger" />
                                        <xs:element name="unit" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="keyname">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Za-z0-9]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="positiveDecimal">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="boundedDecimal">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="wasteAllocation">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DEFAULT"/>
            <xs:enumeration value="MANUAL"/>
            <xs:enumeration value="RESOURCES"/>
            <xs:enumeration value="EXERGY"/>
            <xs:enumeration value="COST"/>
            <xs:enumeration value="IRREVERSIBILITY"/>
            <xs:enumeration value="HYBRID"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="flowType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="INTERNAL"/>
            <xs:enumeration value="RESOURCE"/>
            <xs:enumeration value="OUTPUT"/>
            <xs:enumeration value="WASTE"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="productType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PRODUCTIVE"/>
            <xs:enumeration value="DISSIPATIVE"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="formatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="EXERGY"/>
            <xs:enumeration value="EXERGY_COST"/>
            <xs:enumeration value="EXERGY_UNIT_COST"/>
            <xs:enumeration value="GENERALIZED_COST"/>
            <xs:enumeration value="GENERALIZED_UNIT_COST"/>
            <xs:enumeration value="DIAGNOSIS"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ctorrescuadra/TaesLab/Examples/ccpoly/ccpoly_model.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../plant_model.xsd">
    <ProductiveStructure>
        <flows>
            <key>G1</key>
            <type>RESOURCE</type>
        </flows>
        <flows>
            <key>G2</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>G3</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>G4</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>G5</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>G6</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>G7</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>G8</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>V1</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>V2</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>V3</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>V4</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>WAC</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>WGT</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>WST</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>WCP</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>GN</key>
            <type>RESOURCE</type>
        </flows>
        <flows>
            <key>WN</key>
            <type>OUTPUT</type>
        </flows>
        <flows>
            <key>COLD</key>
            <type>OUTPUT</type>
        </flows>
        <flows>
            <key>HEAT</key>
            <type>OUTPUT</type>
        </flows>
        <flows>
            <key>G9</key>
            <type>WASTE</type>
        </flows>
        <flows>
            <key>QCON</key>
            <type>WASTE</type>
        </flows>
        <processes>
            <key>AC</key>
            <description>Air Compressor</description>
            <fuel>WAC</fuel>
            <product>G2-G1</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>CC</key>
            <description>Combustion chamber</description>
            <fuel>GN</fuel>
            <product>G3-G2</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>GT</key>
            <description>Gas Turbine</description>
            <fuel>G3-G4-G6</fuel>
            <product>WGT+WAC</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>HRSG</key>
            <description>HRSG</description>
            <fuel>G4-G5</fuel>
            <product>V1-V4</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>ST</key>
            <description>Steam Turbine</description>
            <fuel>V1-V2</fuel>
            <product>WST</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>CP</key>
            <description>Condenser pump</description>
            <fuel>WCP</fuel>
            <product>V4-V3</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>GEN</key>
            <description>Generator</description>
            <fuel>WGT+WST</fuel>
            <product>WN+WCP</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>REF</key>
            <description>Refrigerator</description>
            <fuel>G6-G7</fuel>
            <product>COLD</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>HE</key>
            <description>Heater</description>
            <fuel>G7-G8</fuel>
            <product>HEAT</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>STCK</key>
            <description>Stack</description>
            <fuel>G5+G8</fuel>
            <product>G9</product>
            <type>DISSIPATIVE</type>
        </processes>
        <processes>
            <key>CND</key>
            <description>Condenser</description>
            <fuel>V2-V3</fuel>
            <product>QCON</product>
            <type>DISSIPATIVE</type>
        </processes>
    </ProductiveStructure>
    <ExergyStates>
        <States state="Reference">
            <exergy>
                <key>G1</key>
                <value>0</value>
            </exergy>
            <exergy>
                <key>G2</key>
                <value>251434.7398</value>
            </exergy>
            <exergy>
                <key>G3</key>
                <value>800981.4355</value>
            </exergy>
            <exergy>
                <key>G4</key>
                <value>238347.4756</value>
            </exergy>
            <exergy>
                <key>G5</key>
                <value>17248.7222</value>
            </exergy>
            <exergy>
                <key>G6</key>
                <value>2973.558</value>
            </exergy>
            <exergy>
                <key>G7</key>
                <value>467.4062</value>
            </exergy>
            <exergy>
                <key>G8</key>
                <value>241.364</value>
            </exergy>
            <exergy>
                <key>V1</key>
                <value>170942.3944</value>
            </exergy>
            <exergy>
                <key>V2</key>
                <value>14770.3667</value>
            </exergy>
            <exergy>
                <key>V3</key>
                <value>18.4333</value>
            </exergy>
            <exergy>
                <key>V4</key>
                <value>257.9569</value>
            </exergy>
            <exergy>
                <key>WAC</key>
                <value>261432.5</value>
            </exergy>
            <exergy>
                <key>WGT</key>
                <value>256695.1</value>
            </exergy>
            <exergy>
                <key>WST</key>
                <value>141167.47</value>
            </exergy>
            <exergy>
                <key>WCP</key>
                <value>384.03</value>
            </exergy>
            <exergy>
                <key>GN</key>
                <value>718204.1</value>
            </exergy>
            <exergy>
                <key>WN</key>
                <value>389521.2886</value>
            </exergy>
            <exergy>
                <key>COLD</key>
                <value>500.991</value>
            </exergy>
            <exergy>
                <key>HEAT</key>
                <value>91.361</value>
            </exergy>
            <exergy>
                <key>G9</key>
                <value>17490.0862</value>
            </exergy>
            <exergy>
                <key>QCON</key>
                <value>14751.9333</value>
            </exergy>
        </States>
    </ExergyStates>
    <WasteDefinition>
        <wastes>
            <flow>G9</flow>
            <type>MANUAL</type>
            <recycle>0</recycle>
            <values>
                <process>CC</process>
                <value>1</value>
            </values>
        </wastes>
        <wastes>
            <flow>QCON</flow>
            <type>MANUAL</type>
            <recycle>0</recycle>
            <values>
                <process>HRSG</process>
                <value>1</value>
            </values>
        </wastes>
    </WasteDefinition>
    <Format>
        <definitions>
            <key>EXERGY</key>
            <width>11</width>
            <precision>1</precision>
            <unit>(kW)</unit>
        </definitions>
        <definitions>
            <key>EXERGY_COST</key>
            <width>11</width>
            <precision>1</precision>
            <unit>(kW)</unit>
        </definitions>
        <definitions>
            <key>EXERGY_UNIT_COST</key>
            <width>10</width>
            <precision>4</precision>
            <unit>(J/J)</unit>
        </definitions>
        <definitions>
            <key>GENERALIZED_COST</key>
            <width>10</width>
            <precision>1</precision>
            <unit>(kW)</unit>
        </definitions>
        <definitions>
            <key>GENERALIZED_UNIT_COST</key>
            <width>10</width>
            <precision>4</precision>
            <unit>(J/J)</unit>
        </definitions>
        <definitions>
            <key>DIAGNOSIS</key>
            <width>11</width>
            <precision>2</precision>
            <unit>(kW)</unit>
        </definitions>
    </Format>
</root>

=== ctorrescuadra/TaesLab/Examples/steam/steam_model.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../plant_model.xsd">
    <ProductiveStructure>
        <flows>
            <key>B1</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B2</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B3</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B4</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B5</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B6</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B7</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B8</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B9</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B10</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B11</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B12</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B13</key>
            <type>INTERNAL</type>
        </flows>
        <flows>
            <key>B14</key>
            <type>OUTPUT</type>
        </flows>
        <flows>
            <key>B15</key>
            <type>RESOURCE</type>
        </flows>
        <flows>
            <key>B16</key>
            <type>WASTE</type>
        </flows>
        <processes>
            <key>BOIL</key>
            <description>Boiler</description>
            <fuel>B15</fuel>
            <product>(B1-B8)+(B3-B2)</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>HTRB</key>
            <description>HP Turbine</description>
            <fuel>B1-B2-B9</fuel>
            <product>B10</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>LTRB</key>
            <description>LP Turbine</description>
            <fuel>B3-B4</fuel>
            <product>B11</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>LPMP</key>
            <description>LP Pump</description>
            <fuel>B12</fuel>
            <product>B6-B5</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>DRTR</key>
            <description>Dereator</description>
            <fuel>B6+B9</fuel>
            <product>B7</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>HPMP</key>
            <description>LP Pump</description>
            <fuel>B13</fuel>
            <product>B8-B7</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>GEN</key>
            <description>Generator</description>
            <fuel>B10+B11</fuel>
            <product>B12+B13+B14</product>
            <type>PRODUCTIVE</type>
        </processes>
        <processes>
            <key>COND</key>
            <description>Condenser</description>
            <fuel>B4-B5</fuel>
            <product>B16</product>
            <type>DISSIPATIVE</type>
        </processes>
    </ProductiveStructure>
    <ExergyStates>
        <States state="Reference">
            <exergy>
                <key>B1</key>
                <value>51121</value>
            </exergy>
            <exergy>
                <key>B2</key>
                <value>35868</value>
            </exergy>
            <exergy>
                <key>B3</key>
                <value>42109</value>
            </exergy>
            <exergy>
                <key>B4</key>
                <value>5459</value>
            </exergy>
            <exergy>
                <key>B5</key>
                <value>118.7</value>
            </exergy>
            <exergy>
                <key>B6</key>
                <value>218.6</value>
            </exergy>
            <exergy>
                <key>B7</key>
                <value>2359</value>
            </exergy>
            <exergy>
                <key>B8</key>
                <value>2639</value>
            </exergy>
            <exergy>
                <key>B9</key>
                <value>4696</value>
            </exergy>
            <exergy>
                <key>B10</key>
                <value>9739</value>
            </exergy>
            <exergy>
                <key>B11</key>
                <value>31517</value>
            </exergy>
            <exergy>
                <key>B12</key>
                <value>115.9</value>
            </exergy>
            <exergy>
                <key>B13</key>
                <value>314.6</value>
            </exergy>
            <exergy>
                <key>B14</key>
                <value>40000</value>
            </exergy>
            <exergy>
                <key>B15</key>
                <value>129713</value>
            </exergy>
            <exergy>
                <key>B16</key>
                <value>5340</value>
            </exergy>
        </States>
        <States state="Operation">
            <exergy>
                <key>B1</key>
                <value>49259</value>
            </exergy>
            <exergy>
                <key>B2</key>
                <value>36252</value>
            </exergy>
            <exergy>
                <key>B3</key>
                <value>42560</value>
            </exergy>
            <exergy>
                <key>B4</key>
                <value>5517</value>
            </exergy>
            <exergy>
                <key>B5</key>
                <value>120</value>
            </exergy>
            <exergy>
                <key>B6</key>
                <value>220.9</value>
            </exergy>
            <exergy>
                <key>B7</key>
                <value>1269</value>
            </exergy>
            <exergy>
                <key>B8</key>
                <value>1530</value>
            </exergy>
            <exergy>
                <key>B9</key>
                <value>2835</value>
            </exergy>
            <exergy>
                <key>B10</key>
                <value>9384</value>
            </exergy>
            <exergy>
                <key>B11</key>
                <value>31854</value>
            </exergy>
            <exergy>
                <key>B12</key>
                <value>117.2</value>
            </exergy>
            <exergy>
                <key>B13</key>
                <value>296.3</value>
            </exergy>
            <exergy>
                <key>B14</key>
                <value>40000</value>
            </exergy>
            <exergy>
                <key>B15</key>
                <value>130587</value>
            </exergy>
            <exergy>
                <key>B16</key>
                <value>5397</value>
            </exergy>
        </States>
    </ExergyStates>
</root>
